### ISSUE TITLE
Change battery warning threshold

### ISSUE THREAD

**Issue by shad0matic** [pwr-Solaar/Solaar#1005]
Using Solaar version : 1.0.1
keyboard : logitech MX Keys
Request : possibility to change battery warning threshold in config file

Hi,

Thanks for the great work, I'm using Solaar with Logitech MX Keys ans Logitech Vertical mouse and it works great,
just a minor annoyance with the fact that Solaar issues a warning as soon as battery reaches 50% or below on my keyboard,
I feel it would be more appropriate to warn only around 25-30%.

Could it be possible for this threashold to be a setting in config file please ?
That'd be great !

Olivier

**Comment by pfps** [comment]
Precisely what warning is being issued?  Please provide screenshot or output  of `solaar show`.

**Comment by shad0matic** [comment]
Here is the warning,
the exclamation mark icon is also present in solaar tray icon

![screenshot_solaar_2020-11-19](https://user-images.githubusercontent.com/8254476/99658152-633af500-2a5f-11eb-9831-7f8ffda69221.png)

**Comment by pfps** [comment]
This is either a problem with your icon theme or a problem that has been fixed in the current version of Solaar.  

As far as I can tell, the current version of Solaar is using the icon named `battery-good` for this battery level and your theme may have an inappropriate icon for this name.   To check, run `gtk3-icon-browser` (you may have to install it first) and search for the `battery-good` or `battery-good-symbolic` icon.

You should also update to a newer version of Solaar.   The current version of Solaar is 1.0.4 and there have been some updates to how Solaar determines which battery icons to use since 1.0.1.

**Comment by pfps** [comment]
This is most likely either a problem with your icon theme or a problem that has been fixed in the current version of Solaar.  

As far as I can tell, the current version of Solaar is using the icon named `battery-good` for this battery level and your theme may have an inappropriate icon for this name.   To check, run `gtk3-icon-browser` (you may have to install it first) and search for the `battery-good` or `battery-good-symbolic` icon.

You should also update to a newer version of Solaar.   The current version of Solaar is 1.0.4 and there have been some updates to how Solaar determines which battery icons to use since 1.0.1.

**Comment by shad0matic** [comment]
Thank you for the rapid answers,
indeed by updating to Solaar 1.03 from ppa the problem is fixed.
Could find how to browse icons on my linux Mint 20, the gtk3-icon-browser doesnt seem available in my repos,
since updating solaar fixed it I won't look further.

Thank you again for your help !

**Comment by pfps** [comment]
gtk3-icon-browser is probably available as part of the GTK3 development package.   On Fedora this is gtk3-devel, but the name might be different in Mint.

Older versions of Solaar tried hard to pick the best icons, but this just wasn't possible so newer versions have a much simpler icon naming scheme.  It looks as if your theme had incorrect icons for the icon names that Solaar used to use.

**Comment by shad0matic** [comment]
Just in case it might serve someone else later, for linux Mint (and probably Ubuntu too), the package providing the icon browser  is gtk-3-examples
and the icon that was used by solaar 1.0.1 was apparently "battery-caution-symbolic", now using solaar 1.0.3 It's using "battery-full-symbolic" instead which is perfect for me.

Thanks again for your help

**Comment by mat-m** [comment]
Hello,

Same issue here, solved by 1.0.3.
But now, I have the desktop icon and not the symbolic one (icon `battery-good`):
![solaar_1](https://user-images.githubusercontent.com/1039753/103043243-808e4200-457c-11eb-851d-828c82567b17.png)
![solaar_2](https://user-images.githubusercontent.com/1039753/103043248-82f09c00-457c-11eb-85ac-4505a2e27366.png)

**Comment by pfps** [comment]
To use symbolic icons you need `--battery-icons symbolic` in the current version of Solaar.  Use `solaar --help` for information on Solaar options.

**Comment by mat-m** [comment]
@pfps: thanks for this. Nice additions

**Comment by mat-m** [comment]
FTR, and if others get here via google: You need to amend the autostart shortcut. For me, it was in Cinnamon startup launchers, which are *not* desktop files in .config/autostart.
My command is now `solaar -w hide -b symbolic`
