### ISSUE TITLE
Rename individual 'Unifying Receiver' devices?

### ISSUE THREAD

**Issue by Noughtnaut** [pwr-Solaar/Solaar#1008]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.0.1
- Distribution: Ubuntu MATE 20.04 LTS
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-54-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): n/a

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have more than a single Unifying Receiver plugged into my machine, because they both show up with the same name. I have small stickers on the dongles, it would be nice to be able to also distinguish them in software.

**Describe the solution you'd like**
I would like to be able to attach a text label to each individual Unifying Receiver (and for that matter, perhaps also to devices, because I have several identical mice and keyboards).

**Describe alternatives you've considered**
When I need to tell them apart, I have to unplug them and see how the Solaar device listing is reflecting the change.

**Additional context**
I know I am not using the most recent version right now, but I also know that the most recent version does not address this issue.

**Comment by pfps** [comment]
It's not going to be trivial to add this capability because Solaar does not have a saved state for receivers.  The information pane does provide distinguishing information for receivers and devices in the form of their serial number.  You could label your receivers with part of that number.  This would also work with most devices.

**Comment by Noughtnaut** [comment]
Yeah, I was expecting that sort of reply. To tell you the truth, I never considered writing (part of) the serial on the receivers until just after I submitted this request. :-)

I shall do just that, though. It's certainly manageable, and I don't want to waste any more of your time on this.

Again, I am most humbly grateful for this excellent piece of software.

**Comment by Massimo-B** [comment]
I got the same idea because I have more than one piece of the same model and can't distinguish them. Looking at the serial number is one option. But if you store the serial number of known devices, you should also be able to have a custom name mapping for the serials, no?
Btw. when trying to distinguish different devices, where are the device settings stored at all? Is that a solaar storage or is it stored on the pointer device itself, or even on the Unify receiver?

**Comment by pfps** [comment]
Solaar stores device information in `~/.config/solaar/config.yaml`.  Devices have very little information that they retain when not active, so Solaar has to do this so that it can reset the device to the state it was in the last time it was active.
