### ISSUE TITLE
Often I need to disable/enable « Mouse wheel resolution » toggle to reactivate this feature

### ISSUE THREAD

**Issue by stephane-klein** [pwr-Solaar/Solaar#1124]
I use Gnome on Ubuntu 20.10 and a [Logistech MX Master 3](https://en.wikipedia.org/wiki/List_of_Logitech_products#Pointing_devices) mouse connected on [Logitech Unifying Receiver](https://en.wikipedia.org/wiki/Logitech_Unifying_receiver).

I use [Solaar](https://github.com/pwr-Solaar/Solaar) manager to configure the mouse wheel resolution configuration (sorry the screenshot is in French):

![HaAyk](https://user-images.githubusercontent.com/54498080/113204614-c0488200-926d-11eb-98c3-483f29ff1c3c.png)

When « Mouse wheel resolution » is enable, page scrolling is "smooth" in all applactions (Gtk, Firefox...).

Issue: often, I need to disable/enable « Mouse wheel resolution » (« Résolution de la molette ») toggle to reactivate this feature.

I have more or less posted the same question on AskUbuntu: [What is the "official" way to configure Mouse wheel resolution on Gnome (instead Solaar)](https://askubuntu.com/posts/1327690/edit)

Best regards,
Stéphane

**Comment by CheckYourFax** [comment]
This is still a problem today: The scroll resolution is set twice: once by the kernel, and then again upon opening Solaar, causing insanely fast scrolling. This is default behavior, so I think this is still something to be addressed. This happens even after everything is setup. 

On another note: the standard input drivers are insanely flawed because it tends to disable the high resolution scrolling on a window after some time of inactivity (when the mouse turns off into idle mode) and only sets it up again after un+refocusing the window. I find that disabling the high resolution in Solaar is the only way to get a consistent scrolling experience.

Tested on: G502 X Lightspeed.

**Comment by Rongronggg9** [comment]
> I think this is still something to be addressed

FYI, https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f0866517be9345d8245d32b722574b8aecccb348

**Comment by pfps** [comment]
Solaar defaults the scroll resolution setting to "ignore" (for new devices) so Solaar should not be setting the resolution in these cases.  You can also set the scroll resolution setting to "ignore" yourself.

Other than that there isn't much that Solaar can do.  The driver does blind changes of the scroll resolution so it is hard to interact with.  There is also a timing problem because a single HID++ write to the device affects several aspects of the scroll wheel (resolution, direction, diversion).  Solaar tries to get around this problem, but the driver doesn't.  The commit mentioned above might help.
