### ISSUE TITLE
Wheel Resolution option is missing for Logitech MX Master 3 in 1.0.5

### ISSUE THREAD

**Issue by Vanderhoof** [pwr-Solaar/Solaar#1132]
In new version option for Wheel Resolution is missing for Logitech MX Master 3 mouse. The scrolling became very slow, turning this option on in `config.json` doesn't do anything. Reinstalling older version of Solaar fixes the issue

Here's the latest version window
![Screenshot from 2021-04-08 09-28-42](https://user-images.githubusercontent.com/12543857/113980464-31300100-984f-11eb-9fde-a18769a584f4.png)

Here's the 1.0.1 window:
![Screenshot from 2021-04-08 09-41-49](https://user-images.githubusercontent.com/12543857/113980697-78b68d00-984f-11eb-8fe6-c5b9cf7089b0.png)

Interestingly, after installing the older version you can uninstall it and install the new version and scrolling still works fine until restart.

I am installing Solaar through `apt`

**Comment by pfps** [comment]
Presumably you are installing the Solaar git ppa, which tracks the current version of Solaar on github.

The setting for high res scroll resolution was recently removed.  See PR #1128 and Issues #1061 and #1112.  The underlying reason is that current Linux drivers fiddle with this setting to provide smooth scrolling.   If Solaar changes the setting during or after the driver does its thing then the setting can end up the wrong way around.   This can end up with very fast scrolling or very slow scrolling, depending on how the driver works and the timing of the interactions with the mouse.   (This s my understanding of what is causing the problem, which might not be correct.)

So I removed the setting from Solaar when my personal machine started exhibiting the problem.

I'll probably enhance Solaar to add the ability to ignore a setting.

**Comment by Vanderhoof** [comment]
@pfps Well if someone is experiencing troubles with this setting turned on, they can always turn it off, what about those who need it : }

**Comment by pfps** [comment]
The problem is that if Solaar is managing the setting then it is turning the setting on or off.   This change to the setting can interfere with the way the driver works, resulting in incorrect behaviour either way.

**Comment by Vanderhoof** [comment]
Oh, I understand. Anyway, I've managed to bring back normal scrolling speed by fiddling with `MOUSE_WHEEL_CLICK_ANGLE` in hwdb config file, hope that will stick. Thank you for reply and for this essential app for Linux users.

Looking forward to see workaround for this issue in the future!

**Comment by pfps** [comment]
PR #1135 add the ability to ignore settings and adds the wheel resolution back in.   Please try it out.

**Comment by Vanderhoof** [comment]
@pfps this one works perfectly on my system. The "ignore" setting doesn't seem to do anything for me, but I didn't have problems with wheel resolution setting before, so in my case this is a good thing, I suppose.
