### ISSUE TITLE
 There are two buttons where it is difficult to translate into Japanese

### ISSUE THREAD

**Issue by toda-ryunosuke** [pwr-Solaar/Solaar#1274]
The button captions in the main window have a fixed word sequence.
・Quit Solaar
・About Solaar
The above is difficult to translate into Japanese.
In Japanese...
・Solaarを終了
・Solaarについて

Solaar is a great tool !!

**Comment by pfps** [comment]
The translations do not have to be literal, so feel free to translate into something with the same meaning.  You could update the Japanese translation for Solaar.  See https://pwr-solaar.github.io/Solaar/i18n for information on how to update translations.

**Comment by pfps** [comment]
To change the Japanese translation you update the po/ja.po file in Solaar.  For more information see https://pwr-solaar.github.io/Solaar/i18n

**Comment by viniciusbm** [comment]
I think what @toda-ryunosuke means is that it's impossible to write a proper translation because the format is hard-coded (a translatable string + a space + the program name), which doesn't allow moving the direct object to a different position. 

https://github.com/pwr-Solaar/Solaar/blob/67e40b35e805a75010bf21a75fa8a1d279267b3c/lib/solaar/ui/window.py#L325

https://github.com/pwr-Solaar/Solaar/blob/67e40b35e805a75010bf21a75fa8a1d279267b3c/lib/solaar/ui/window.py#L328

https://github.com/pwr-Solaar/Solaar/blob/4b97ebd64996929c0588206df8d4158368edf9b6/lib/solaar/ui/tray.py#L68

To solve this problem, I think the name "Solaar" should either be part of the translatable strings or added with the expansion of `%s`: 

```python

# Replace these expressions:

_('About') + ' ' + NAME
_('Quit') + ' ' + NAME

# with these:

_('About Solaar')
_('Quit Solaar')

# or these:

_('About %s') % NAME
_('Quit %s') % NAME
```

**Comment by pfps** [comment]
Aah, that makes sense.  Grepping through the code there is another place where a construct like this occurs.  I think that it is a good idea to fix all of them, even though this will affect existing translations.

Any suggestions on a good way to get people to update the other translations?

PS:  Here are the four that should be fixed, I think:
```
lib/solaar/ui/tray.py:    menu.append(make('application-exit', _('Quit') + ' ' + NAME, quit_handler, stock_id='application-exit').create_menu_item())
lib/solaar/ui/action.py:about = make('help-about', _('About') + ' ' + NAME, _show_about_window, stock_id='help-about')
lib/solaar/ui/window.py:    quit_button = _new_button(_('Quit') + ' ' + NAME, 'application-exit', icon_size=_SMALL_BUTTON_ICON_SIZE, clicked=destroy)
lib/solaar/ui/window.py:        _('About') + ' ' + NAME, 'help-about', icon_size=_SMALL_BUTTON_ICON_SIZE, clicked=_show_about_window
```

**Comment by viniciusbm** [comment]
> Any suggestions on a good way to get people to update the other translations?

To reduce the impact on existing translations, I think a good solution would be to append a space and `Solaar` to the corresponding `msgstr` fields of every language, which seem to always come one line after the `msgid`. Using `sed` to make the substitutions: 

```shell 
for f in po/*.po
do
    sed '/^msgid "\(Quit\|About\)"$/{s/"$/ Solaar"/;N;s/"$/ Solaar"/;}' -i "$f"
done
```

**Comment by pfps** [comment]
This is roughly what is done in PR #1279, which was just merged in.
So you should be able to correctly translate these two buttons.

**Comment by viniciusbm** [comment]
@pfps, I've just checked that after #1279 the button texts are still displayed correctly in the languages I have some knowledge of. I don't remember if this is expected, but the translations only worked for me after I ran `./tools/po-compile.sh`.

Unfortunately, I don't know Japanese or any other language that requires the inversion in question, but I think this issue is solved and @toda-ryunosuke can now properly translate those messages into Japanese.

**Comment by pfps** [comment]
I'm not exactly sure when `./tools/po-compile.sh` has to be run.  I think that distributions have to run it themselves as the .mo files are not in git.  I run it just before I generate the PyPi distribution.

I went through most languages and fixed them to run with the new button texts.

Yes, it should now be possible to correctly translate the messages into Japanese.

**Comment by toda-ryunosuke** [comment]
No-impact fix. Great idea.
Japanese has been translated correctly.
Thank you!

**Comment by pfps** [comment]
@toda-ryunosuke The ja.po file had not been updated.  I updated it just now.  You will probably have to run `./tools/po-compile' to see the changes.

There are a few strings that are not translated.  If possible could you update the Japanese translation?  Thanks.

**Comment by toda-ryunosuke** [comment]
![image](https://user-images.githubusercontent.com/33403304/135743549-6d31e14b-40d2-4c88-bc88-87f39c1535c6.png)
It's perfect. I'll work hard on the rest of the translation.Thanks!
