### ISSUE TITLE
Support for Dell Universal Receiver

### ISSUE THREAD

**Issue by greenonline** [pwr-Solaar/Solaar#1330]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`):
- Distribution:
- Kernel version (ex. `uname -srmo`):
- Output of `solaar show` for the target device (if applicable):

<details>

```
OUTPUT HERE
```
</details>

**Is your feature request related to a problem? Please describe.**
No existing problem

**Describe the solution you'd like**
Would you consider supporting the Dell Universal Receiver, which works in pretty much the same way as the Logitech Unifying Receiver? However, the two are not compatible, nor does the Dell appear to be a repackaged/rebadged Logitech receiver.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by pfps** [comment]
If the receiver works the same way, then yes, but  you will have to do most of the work.  However, I expect that there are significant differences, which would make support of the Dell receiver a major task.  Is there documentation on how the receiver works?  Without that you would have to figure out what the messages mean.

Logitech has provided considerable documentation on their HID++ protocol in https://drive.google.com/drive/folders/0BxbRzx7vEV7eWmgwazJ3NUFfQ28?resourcekey=0-dQ-Lx1FORQl0KAdOHQaE1A which has been used to implement Solaar.

**Comment by pfps** [comment]
See also issue #471

**Comment by pfps** [comment]
Closed, for now, as outside the current scope of Solaar.  If documentation can be found for the Dell devices or the protocol reverse engineered, then this issue can be reopened.

**Comment by jeisoncp** [comment]
How you got this documentation from Logitech? Just want to check if there are a similar way on Dell side.

**Comment by pfps** [comment]
I believe that Logitech released this documentation so that third-party software can be written to control their devices.  It was released quite some time ago and I don't know why Logitech made the decision.

It may be that the Dell receiver is just a rebranded Logitech receiver.  To check, find out its USB ID and add a record for it as a _unifying_receiver in lib/logitech_receiver/base_usb.py.   The run `solaar -dd show` as root and see whether information about the receiver shows up.  You could also try the process for adding new devices from https://pwr-solaar.github.io/Solaar/devices
