### ISSUE TITLE
hide status bar icon when no device is connected

### ISSUE THREAD

**Issue by FlyinPancake** [pwr-Solaar/Solaar#1414]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.0
- Distribution: Fedora Linux 35
- Kernel version (ex. `uname -srmo`):  Linux 5.15.12-200.fc35.x86_64 x86_64 GNU/Linux

**Is your feature request related to a problem? Please describe.**
I use my MX Master and MX Keys on my laptop occasionally thus I have Solaar installed to show battery levels and configure some of the settings, but mostly they are not connected. I have a small screen and I'd like to have the option to hide the status icon if solaar has not detected any connected devices.

**Describe the solution you'd like**
If I connect a Solaar compatible device only then does solaar show its battery level, optionally for both devices with little keyboard and mouse icons next to the battery or in the dropdown, separated, so I know the battery levels exactly without opening the app

**Comment by pfps** [comment]
Having multiple little icons instead of one isn't going to work well.   What does work now is that the Solaar menu shows battery levels for devices in the tray menu, which shows up when the tray icon is clicked
Having the tray icon not be visible when there is no device to control sounds good in general.  If there is no device to control then there is little reason to open the Solaar main window.  If the main window needs to be opened when no devices are available this can be done by invoking Solaar, which will not start a second copy of Solaar.

**Comment by pfps** [comment]
PR #1415 unconditionally hides the tray icon when no devices are available.  Check it out and reply whether it meets your desires.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1415, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1415/head:pull_1415
git checkout pull_1415
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1415
git fetch origin pull/1415/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Does PR #1415 solve this issue for you?
