### ISSUE TITLE
Solaar >= 1.1.2 requires python >= 3.8

### ISSUE THREAD

**Issue by Kieltux** [pwr-Solaar/Solaar#1547]
**Information**
Running solaar 1.1.2 on python < 3.8 does not work, but documentation says:
requires Python 3.7+ and requires several packages to be installed

```
# solaar   
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/solaar/i18n.py", line 63, in <module>
    unicode  # noqa: F821
NameError: name 'unicode' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/solaar", line 54, in <module>
    import solaar.gtk
  File "/usr/lib/python3.6/site-packages/solaar/gtk.py", line 29, in <module>
    import solaar.i18n as _i18n
  File "/usr/lib/python3.6/site-packages/solaar/i18n.py", line 69, in <module>
    pgettext = _gettext.pgettext
AttributeError: module 'gettext' has no attribute 'pgettext'
```

**Describe the bug**
The attribute 'pgettext' is added to  gettext with python 3.8.

See: https://docs.python.org/3/whatsnew/3.8.html
gettext[¶](https://docs.python.org/3/whatsnew/3.8.html#gettext)
Added [pgettext()](https://docs.python.org/3/library/gettext.html#gettext.pgettext) and its variants. (Contributed by Franz Glasner, Éric Araujo, and Cheryl Sabella in [bpo-2504](https://bugs.python.org/issue2504).)

**Comment by pfps** [comment]
You are correct.   This is used in one place, where an ambiguous English word needs to be translated.

The question is what to do.  One way forward is to remove this function at the cost of having less-than-ideal translations.  The other way forward is to update the Python version requirement.

@viniciusbm Do you have a preference?

**Comment by viniciusbm** [comment]
The function `pgettext` is used only to show "Key" in this context: 

![image](https://user-images.githubusercontent.com/11576083/162630856-ddeb8271-fbf2-47ae-a3c3-d276ab614822.png)

... because the same word appears in this context: 

![image](https://user-images.githubusercontent.com/11576083/162631053-3b76558a-333f-4671-921a-8a2c634be764.png)

I used that function because in Portuguese the first one (key as in key-value) is "chave", and the second one (a type of button, as in keyboard key) is "tecla". 

Using either word in both cases can be very confusing for users who do not understand English. On the other hand, it may be too soon to update the Python version requirement, given that [Python 3.7 will be supported until June 2023](https://devguide.python.org/#status-of-python-branches). 

I think there's a better solution: "key" [here](https://github.com/pwr-Solaar/Solaar/blob/c53c77f42715af795af880fc558a4ef1fefe6531/lib/solaar/ui/diversion_rules.py#L2069) could be replaced with "item", which is probably easier to understand even in English, considering that this meaning of "key" is specific to software development and related areas.

**Comment by pfps** [comment]
OK, that sounds reasonable.    PR #1548 should fix this issue.



To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1548, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1548/head:pull_1548
git checkout pull_1548
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1548
git fetch origin pull/1548/head
git reset --hard FETCH_HEAD
```
