### ISSUE TITLE
Can't find documentation RE: Mouse Gestures for MX Master v1

### ISSUE THREAD

**Issue by jaaxx** [pwr-Solaar/Solaar#1622]
Are mouse gestures even available for MX Master v1?  I can't find anything in the docs and gesture rules are definitely NOT working.

**Comment by pfps** [comment]
Mouse gestures, like other Solaar capabilities, are only available if the device has the features that support the capability (unless there is a bug in Solaar).   If you provide the output of `Solaar show` then I can determine for sure whether your mouse supports mouse gestures.

**Comment by jaaxx** [comment]
[https://pastebin.com/Tid9LvjU](url)  solaar show output for MX Master v1

**Comment by pfps** [comment]
Your device does not have any key that has the rawXY flag, which is required for mouse gestures in Solaar. This is so even though your mouse has a Mouse Gesture Button.  Windows Logitech software may be able to intercept regular mouse movement reports, because there is a special Logitech driver for their devices in Windows, but Solaar cannot.
