### ISSUE TITLE
Implement an async set-command for devices that can go offline

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1710]
**Is your feature request related to a problem? Please describe.**
Some settings can only be changed when the device is online, but it is not given that the device is actually online when it is changed.

**Describe the solution you'd like**
Some settings are done before other following events that will make the device go online. For example a `change host` before typing. That makes it possible to let the change request linger on for a few seconds when the device is offline, in anticipation of it going online when the user starts typing. When the device goes online the change is done before any following events are processed.

An obvious implementation is to make a `set-async` that has non-blocking behavior, and which does the change within some timeframe or fail if the device does not go online within the timeframe.

**Describe alternatives you've considered**
In some cases it is possible to show a notification to the user informing him/her the change request has failed.

**Comment by pfps** [comment]
Solaar changes setting by communicating with the device, which can only happen when the device is online.   The Solaar GUI should only allow changes when the device is online.  Actual changes to the device should be done in a non-blocking manner, except that access to the device is synchronized so that there are not two commands outstanding to the device at the same time.  

If you want to use the CLI to do things like change host then why not use Linux scripting to delay the command?

**Comment by jeblad** [comment]
The system has a rather unpredictable behavior, the channel is flaky and the device goes offline in an unpredictable manner. In my opinion you must use async code when that is the case.

**Comment by pfps** [comment]
In the GUI it is possible that the device goes offline between the time a setting is changed in the GUI and the new value is written to the device.  Solaar protects against this by performing the change in a separate thread and signalling a problem in the main window.   Solaar stores the new value in its configuration information even before trying to write the value to the device.  So if the device is offline the Solaar GUI should try writing the value again when the device comes online again.

The Solaar CLI is very low level and doesn't retry commands.   But it similarly causes the new value to be remembered in the Solaar configuration information so even if a change fails it will be picked up by the Solaar GUI the next time the GUI is run.

**Comment by pfps** [comment]
I saw the wiki entry you created and now I understand the problem.   For settings that Solaar does not remember (currently just change_host) if the attempt to change the setting fails for some reason it will be reattempted when the device reconnects.

But the solution is elusive.  As far as I know there is no way to determine why the device cannot be contacted.   It could be that the device is in a power saving mode, it could be that the device has been turned off, it could be that the device has already changed hosts, it could be that the device has been paired with some other receiver, etc.  In some of these cases Solaar the right thing to do is probably to retry the change_host but in others it is probably not.

But the problem is not whether Solaar is using synchronous methods.  It is that Solaar does not retry the command if it fails because this setting is not remembered by Solaar.  I suggest you edit the title of the issue.  Suggestions for how to resolve the issue are welcome as well.

**Comment by pfps** [comment]
The big problem here is how long to wait.  It is entirely possible that the user switches from one host to another and back again within a few seconds using the keyboard only so that the mouse is offline the entire time.  When the mouse comes back online it will be switched to the other host, surprising the user.

As far as the keyboard not switching that is rather unusual if you have the rule trigger on the keyboard host switch key being pressed as the keyboard should be online then.  But there is no response from the device for a host switch command to a host number that has been set up in the device.

**Comment by jeblad** [comment]
If you use the keyboard to switch both keyboard and mouse, but the mouse is offline, and then you switch back again, then you can kill the pending switch on the mouse. That means a state must be maintained, and a condition to act on that state must be made.

I expected the keyboard to be online after I pressed a key, but that seems not to be correct. I'm not sure what happen, but it seems like some key presses are lost. If I wait a few seconds and try again it usually work. Perhaps it takes some time to reestablish the connection.

**Comment by pfps** [comment]
I was trying to think of a way to add the delayed switch in a manner that isn't too much work and that can be used for other capabilities.  Your suggestion seems like considerable work and also has a problem if the mouse comes back before the keyboard.  

As far a missed switches for the keyboard, it may be that if the keypress wakes up the keyboard then it is not prepared to switch hosts immediately.  The solution here is probably just to try again.  That is not ideal, but having Solaar wait for a bit and then try again is also not great as keypresses will likely go to the wrong host.

**Comment by pfps** [comment]
One thing to do is to try to find out just what is happening when the host switch fails on either the keyboard or the mouse.  To do that requires running Solaar with debugging output turned on, i.e., as `solaar -ddd`.

**Comment by jeblad** [comment]
The [Example: Host Switch Channel](../wiki/Example:-Host-Switch-Channel) use the host switch keys on the keyboard, as a lost transfer of the mouse does not pose an security issue, and a failed rule on the keypress is pretty obvious. Using the smart shift button on the mouse may lead to an security issue, because you may fail to notice that the typing goes to a wrong window on another machine. I.e. typing a password into an IRC client for example.

I tried to log what happen for the keyboard some time ago, and I noticed some changes in the signalling. It wasn't just the device going offline, something else was sent from the device. I could not figure out what was going on. Perhaps there is some difference between the device going offline and the device switching to another host.

**Comment by pfps** [comment]
If you can get a new debugging log from Solaar I might be able to figure out whether something is going wrong.

**Comment by pfps** [comment]
I added a new rule condition to test whether a device is active.  (It's not in the rule editor yet.)  This would allow for writing a switch rule like:
```
---
- Key: [Host Switch Channel 2, pressed]
- Rule:
  - Active: 198E3EB8
  - Set: [43DAF041, change-host, 1]
  - Set: [198E3EB8, change-host, 1]
  - Execute: [notify-send, Switched keyboard and mouse to idefix]
- Set: [43DAF041, change-host, 1]
- Execute: [notify-send, Switched keyboard to idefix.  Mouse not active, it will have to be switched manually]
...
```
It could also be used to abort the entire switch and just pop up a notification to activate the mouse.

**Comment by pfps** [comment]
PR #1719 has the new rule condition and the rule editor can edit it.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1719, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1719/head:pull_1719
git checkout pull_1719
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1719
git fetch origin pull/1719/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
@jeblad The Active rule condition is now in Solaar in this repository.   Does it help to solve your problem.

**Comment by jeblad** [comment]
It seems like the switching is more predictable, but that is only my experience of the observed behavior.

It also seems like the keyboard (MX Keys on Unifying receiver) does not always respond to keypress on the key for Host Switch Channel. Seems like a long press doesn't help, it must be a double tap. That isn't necessary when set up for regular switching. When the keypress is neglected there are no notification, so I guess there are no event going to solaar? Strange thing is, the single press works for the first time after a restart of solaar.

**Comment by pfps** [comment]
To see what is going on with the need for the double keypress you would have to run solaar as `solaar -ddd` and post the output from around the time that you need the double keypress.  That will show what the keyboard is producing - if only one keypress comes from the keyboard then there is likely nothing that can be done.

Regular switching, i.e., not diverting the key, is done within the device itself and thus doesn't need a keypress sent to Linux.

**Comment by pfps** [comment]
I see two switches away and back.

I think the problem is that when the device switches away the message indicating the key release is not sent, because the device is switched away before the key is released.  Solaar cannot then realize that the key has been released.  So the first key message is treated as a no-op because Solaar remembers the key-down state.  The second key message after switching back then clears the key-down state so that the third key message does the right thing.  The problem here is that the device doesn't send key-press and key-release messages, just a message with the keys that are down. So software has to remember the previous state and see what is different.

Switching the rules to trigger on key release would probably work much better.   Even if the key release when switching back ends up being caught by Solaar it shouldn't trigger any rules because it will be treated as a no-op.

I'm not sure what can be done to completely fix the problem.  For now I'll add this to the known issues list.

**Comment by jeblad** [comment]
The user can accidentally hold the key down slightly longer, and then release it on the other machine. What if Solaar clears the remembered key-down state for a returning device, and then only re-enable the state for a key press?

**Comment by pfps** [comment]
If the rules trigger on the key release then things would normally work out OK.  

But, yes, clearing out the state when a device shows up would also help.  But then there is a race between the first keypress and Solaar clearing the state.  I expect that there is no solution that works in all cases, though.

**Comment by pfps** [comment]
The fix for this issue is to add a known issue to the Solaar documentation stating that host switching should be done on key release.   That's about all that can be done.
