### ISSUE TITLE
Leave the MX Keys/MX Mechanical backlight on

### ISSUE THREAD

**Issue by viossat** [pwr-Solaar/Solaar#1902]
Some users would like to leave the backlight of their keyboards on, or at least turn it off after a much longer inactive period than the default ~3 seconds. [However Logitech seems to ignore this request for 2 years.](https://www.reddit.com/r/logitech/comments/kpgq7n/mx_keys_backlight_always_on/)

After some research the only workaround I found is a custom script which regularly executes the following Solaar command:
`solaar config <DEVICE> backlight 1`
However every time this command is executed the backlight is turned off for a short period of time, destroying the user experience.

Is there any way to fix this issue through Solaar?

**Comment by pfps** [comment]
There does not appear to be any way to change the backlight duration using the backlight feature in these keyboards.  To be able to do so would require new firmware for the keyboard, which can only be done by Logitech.

You say that you can force the backlight on using `solaar config Keys backlight 1`.  That doesn't work on my Craft Keyboard, which has the same backlight feature, but what does work is setting the backlight to off and then on again.  I suspect that that is what you are doing because you mention that the backlight is off for a short period.

I tried directly sending the messages to turn the backlight off and then on to see if this works without noticeable flashing, but even this causes the backlight to be off for a short while.

So I think the only way forward is to try to press Logitech to upgrade the firmware on the keyboards.  I don't expect this to work, though, as it would require significant effort on the part of Logitech.
