### ISSUE TITLE
Battery percentage checking in the rule editor

### ISSUE THREAD

**Issue by tester1121** [pwr-Solaar/Solaar#2000]
I would like to disable the backlight on my MX Keys keyboard when the battery is less than 10%. I do not know how to do this in the rule editor (maybe a combination of the Feature and Report conditions), or if it is even implemented.

**Comment by pfps** [comment]
This is almost possible, but probably not exactly as you want.  As you suspect a combination of Feature and Report conditions is needed but you also need a TestBytes condition.  But crafting the conditions is not trivial.  Your MX Keys keyboard probably uses the BATTERY STATUS feature.  Look at the output from `solaar show` to check for sure.  Your MX Keys probably also only reports a few levels (probably including 20% but maybe not 10%) so you might not be able to turn the backlight off when you want to.   To figure out what the notification messages you need to know what the battery notification message look like.   There are descriptions of several of these in the Logitech HID++ Google Drive.   The battery messages are actually in one of the oldest documents there that described the HID++ 2.0 protocol.  Download https://drive.google.com/drive/folders/0BxbRzx7vEV7eWmgwazJ3NUFfQ28?resourcekey=0-dQ-Lx1FORQl0KAdOHQaE1A and look for the section on notification 0x1000.  There you will see that the report number for notifications (Logitech calls them events) is 0  so you need Feature 0.   You will also see that the first byte of the notification is the battery level.  So you want to check for numbers between 1 and 21 (unless you know that your keyboard reports at level 10).  So the TestBytes condition has arguments 0 1 1 21

Testing whether this actually works is not going to be easy because your keyboard will only emit the notifications occasionally.  I suppose you could try charging the keyboard just past a level causes a notification.

**Comment by tester1121** [comment]
This does work. Thank you!
