### ISSUE TITLE
Highlight rules when they are triggered in the rules editor

### ISSUE THREAD

**Issue by MiguelGuthridge** [pwr-Solaar/Solaar#2044]
**Is your feature request related to a problem? Please describe.**
Writing rules for Solaar is quite a challenge, and needing to check if the rule you've written matches can be frustrating, since I need to manually hit save and then change to a different window to see if the rule matches.

**Describe the solution you'd like**
While the rules editor window is open, it should highlight the rules that get triggered so that it's clear whether the rule is working or not. It'd be especially nice if the triggers are checked without the need to save (obviously without following through with the actions).

**Describe alternatives you've considered**
UI improvements to the rules editor to make it easier to understand. This is probably necessary regardless, but highlighting the matched rules will make it a little easier.

**Additional context**
Here is a mock-up of what I imagine this would look like:
![image](https://user-images.githubusercontent.com/31365175/230716472-6ca1c674-ed56-46bd-8828-8a9a1103ad72.png)

Some notes on the design:
* For the first rule, it is highlighted in its entirety to show that the entire rule matched, and that the action was taken.
* For the second rule, only the first condition is highlighted to show that although that condition matched, other conditions did not, and therefore the rule did not execute in its entirety.

**Comment by pfps** [comment]
This does sound like a useful enhancement.

It is possible to show progress of rule execution while editing rules without saving them as the rule editor makes changes directly to the Solaar rules.   Saving is just necessary for the rules to be saved so that they are retained the next time Solaar is run.  Run Solaar as `solaar -ddd`, open the rule editor, make changes, and trigger a rule.   Rule execution will show up in the window where Solaar is being run.

**Comment by pfps** [comment]
It turns out that there are two problems with showing rule execution in the rule window.  First, the rule window uses Gtk TreeView, which doesn't have facilities for highlighting rows.  (How does selection highlight the selected row?  I don't know.)  Second, highlighting would be ephemeral as HID++ notifications come in quite regularly and would overwrite the highlighting.  

So I think that you are stuck with using `solaar -ddd`.
