### ISSUE TITLE
Repeated increment rule for brightness in mouse gestures

### ISSUE THREAD

**Issue by a-v** [pwr-Solaar/Solaar#2094]
**Information**

- Solaar version (`solaar --version` or `git describe --tags`): 1.1.9+git2021-444fd4a
- Distribution: Linux Mint 21.1
- Kernel version (ex. `uname -srmo`): Linux 5.15.0-76-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): the mouse is a Logitech M720 (mouse gestures enabled)

**Is your feature request related to a problem? Please describe.**

For context, I am primarily a windows user so Logitech Options is my default software. Solaar is an amazing device manager and I have not had any complaints with it, and major props to the rule editor, it is quite intuitive to use for most mappings. 

In logitech options, mapping the brightness up key to mouse gestures allows me to hold the thumb mouse gesture button and drag my mouse up to continuously increase the brightness. 

**Describe the solution you'd like**

I am wondering whether a similar Solaar rule can be made in the Rule Editor to continually increase the brightness. I used the command `solaar -dd` to see that there is a listener notification, however this notification is only output to the terminal when the mouse gesture button is released:
![image](https://github.com/pwr-Solaar/Solaar/assets/60872861/1c3c12f9-32a1-4057-bd40-69fe97c5721e)

**I want to split the distance mapping of moving up (since "-14" in the screenshot above is a measure of travel distance) into chunks of say -1, so that the brightness button is called at every increment of -1 'distance'.** 

**Describe alternatives you've considered**
I currently have it set at a single key press, and it increases the brightness once after these three steps: 1) press the mouse gesture button 2) drag up 3) release the button.

Also, I tried using the "depress" option in the key press action, however I am unsure about what condition I shoud set to "release" the key press once I have released the mouse gesture button.

I tried logiops a while ago, and although it had this feature, it was a bit glitchy, if I remember correctly. Not sure when or why exactly, but I switched to Solaar some time back.

**Additional context**
I also ran `solar -ddd` and I realized that there is a lot of output when i hold the button and move up, basically it seems like a lot of rule editor conditions are being checked, so I thought maybe it is possible to evaluate a condition repeatedly, was unable to discern much other than that.

Please let me know if this already exists and I am missing something!

**Comment by pfps** [comment]
The output you see from `solaar -ddd` is mostly the notifications as the mouse moves.  These notifications are examined within Solaar and used to determine the direction the mouse has moved and when the mouse has stopped for a while.


It appears that you want something similar to Sliding DPI, where moving the mouse while a specified button is down changes the DPI.   The difference is that changing the DPI is something that Solaar does and changing the brightness requires an external command.  

All that Solaar would do, if this kind of thing is implemented, is call an external program as the mouse is moved.   The big problem is how to set up the API and how to have rapid feedback so that brightness is actually changed as the mouse moves.   I don't think the second is achievable, unfortunately.

But maybe all you want is to be able to change brightness once, but by the amount the mouse has moved.   Solaar could compute that and make it available to the rule system.   Getting the API right might require some work and some interaction.

**Comment by pfps** [comment]
Is there anything else to do here?

**Comment by a-v** [comment]
Not at the moment, thanks for the help
