### ISSUE TITLE
Package build failed on PPA

### ISSUE THREAD

**Issue by Onplick** [pwr-Solaar/Solaar#2186]
I looked on PPA and it looks like multiple builds failed for the latest release which leads to only previous version being available from PPA repository.
Build status available here:
https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa/+packages

```
$: sudo apt policy solaar

solaar:
  Installed: (none)
  Candidate: 1.1.9+git2025-4160b0e~ubuntu22.04.1
  Version table:
     1.1.9+git2025-4160b0e~ubuntu22.04.1 500
        500 https://ppa.launchpadcontent.net/solaar-unifying/ppa/ubuntu jammy/main amd64 Packages
        500 https://ppa.launchpadcontent.net/solaar-unifying/ppa/ubuntu jammy/main i386 Packages
        100 /var/lib/dpkg/status
     1.1.1+dfsg-1 500
        500 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://pl.archive.ubuntu.com/ubuntu jammy/universe i386 Packages
```

**Comment by pfps** [comment]
@muzena Can you look at this?

**Comment by pfps** [comment]
You could use pip to install the current version of Solaar.  If you have a recent version of Solaar already installed you should not have to worry about installing the Solaar udev rule and all you should need to do is `pip install solaar`.   Solaar should then be available at `~/.local/bin/solaar`.

**Comment by pfps** [comment]
@muzena Can you look at this?

**Comment by ximex** [comment]
and it would also be nice if you could add builds for `mantic`

**Comment by ximex** [comment]
i don't mean the original repository from ubuntu. I mean that ppa: https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable
isn't that from the solaar devs?

**Comment by pfps** [comment]
Oh, you mean add a build for a different version of Ubuntu.  That is in the purvue of the person who is maintaining this distribution.

**Comment by pfps** [comment]
The person who maintains this repository hasn't done anything to it for a while now so maybe it should be considered abandoned.   If anyone is interested in taking it over please let me know and I can try to figure out how you can take over.  The amount of work needed to keep it up to date should be minimal after the work needed to figure out how updates to Solaar are gathered and how the images are generated.

**Comment by antonsoroko** [comment]
@pfps 
I also was wondering why I do not get updates :-) So I found out this (quick documentation about ppa: https://help.launchpad.net/Packaging/SourceBuilds/Recipes ):

1. [Solaar stable ppa](https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable) build are still using git tag `1.1.8`, see [recipe](https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-git). Thus it always old.

2. [Solaar git ppa](https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa) builds are using `master` branch (this is ok), see [recipe](https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-git).

But builds are failing after https://github.com/pwr-Solaar/Solaar/commit/91f1894e8bce3c965ce9335629f1346bb6d12ee4 commit.
Surprisingly, packaging scripts are located in a fork and in a special branch. It would make much more sense to have `packaging/debian` directory in this (original) repository, IMHO.

So build [script](https://github.com/muzena/Solaar/blob/python3-new1/packaging/debian/control) is old and it misses the `dbus-python` package.

3. **On a bright side**, Debian maintainer of `solaar` package does update packaging scripts on regular basis.
See https://salsa.debian.org/debian/solaar/-/blob/debian/latest/debian/control?ref_type=heads
(Btw, scripts for PPA are based on this Debian scripts).


And as you can see
https://packages.debian.org/search?keywords=solaar&searchon=names&suite=all&section=all
https://packages.ubuntu.com/search?keywords=solaar&searchon=names&suite=all&section=all

Debian and Ubuntu have latest versions of package in testing versions of distributions. And less latest in stable versions of distros.
For mine Ubuntu 23.10 Mantic - I manually downloaded 1.10 `.deb` package and it works fine. But of course this is not sustainable solution.

Maybe it still makes sense to keep those PPAs alive in order to get latest versions of solaar ASAP, but to avoid duplication of work and possible obsolescence of scripts (like we have right now), packaging scripts should be somehow synchronized with Debian repo.

Or maybe contacting Debian maintainer (Stephen Kitt) to get an advice would be more reasonable idea.

**Comment by skitt** [comment]
I’m not familiar with PPA builds, I can’t really help with that.

To make things easier for Debian users, I can add the latest version to the backports repository; but that will only help Debian users, not Ubuntu etc.

**Comment by skitt** [comment]
Of course — all I had in mind was making the latest release in the backports repository, so that users of the current Debian stable release can easily install it (so they could get 1.1.10 rather than 1.1.8).

**Comment by antonsoroko** [comment]
@pfps @skitt 
I think idea of [Solaar stable ppa](https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable) was to build and distribute new releases of solaar faster than Debian/Ubuntu maintainers do. But that PPA is stale now.
If Debian package will be update every time solaar has new release - then I do not think that this PPA is needed.

---

As I understand, Debian maintainers maintain many packages simultaneously, and I guess they also do some tests before releasing a package, thus often we have older version of packages. Correct me if I am wrong.

**Comment by skitt** [comment]
> As I understand, Debian maintainers maintain many packages simultaneously, and I guess they also do some tests before releasing a package, thus often we have older version of packages. Correct me if I am wrong.

The reason Debian releases have older versions of Solaar is that once a Debian release is frozen, it can’t get newer versions (except for a few packages such as Firefox), it only gets fixes for serious bugs. When Debian 11 was frozen, the current version of Solaar was 1.0.4, so that’s what’s in Debian 11; when Debian 12 was frozen, the current version of Solaar was 1.1.8, so that’s what’s in Debian 12.

The same principle applies to Ubuntu: 23.10 froze with Solaar 1.1.9, 22.04 with Solaar 1.1.1 etc.

**Comment by pfps** [comment]
@skitt Having a backport of Solaar 1.1.10 would be useful, thanks.

**Comment by antonsoroko** [comment]
@pfps looks like you have admin permissions on this PPA - https://launchpad.net/~solaar-unifying/+members#active

I took a quick look at the PPA documentation, so i guess it would be not hard to change "recipe" to use debian build scripts (from the debian repo i mentioned above). then to build a new release version - only "tag name" (e.g. `1.1.10`) should be changed in recipe - mybve a bit annoying, but easy. 

**So, if want - I reconfigure PPA, if you add [me](https://launchpad.net/~antonsoroko) to PPA [members](https://launchpad.net/~solaar-unifying/+members).**

P.S.
I do not see a way to automatically build every new tag - thus manual change of recipe. The only way I see is to create branch (or tag) called `stable`/`release`/`production` and make it to point to latest stable commit, and update it when needed - not sure what is more inconvenient, manually update tag in PPA recipe or updating special git branch.

P.P.S btw, there is a very detailed guide - https://github.com/JoseExposito/touchegg/issues/451#issuecomment-778659016

**Comment by pfps** [comment]
@antonsoroko Thanks.  I need your launchpad user ID to add you, I think.  If you don't want to put it here you can email me at pfpschneider@gmail.com

**Comment by pfps** [comment]
@antonsoroko OK, I added you.  Let me know if you want to be an administrator.

**Comment by pfps** [comment]
@skitt Excellent, thanks.

**Comment by antonsoroko** [comment]
@skitt hi. while i was fixing ppa i have found a "future" issue with packaging.
after https://github.com/pwr-Solaar/Solaar/commit/cf71736920ff85e9f5a082d3a7cfaadfc00af13d commit your patch https://salsa.debian.org/debian/solaar/-/blob/debian/latest/debian/patches/skip-udev-rule-installation.patch?ref_type=heads does not work anymore.
thus next version build will fail like this one - https://launchpadlibrarian.net/711847967/buildlog.txt.gz

i am not sure if it possible to fix packaging right now for future version and also have it backward compatible with current version.

maybe you can come out with some good solution for this issue before new release will be released.
thanks.

**Comment by antonsoroko** [comment]
@skitt i fixed stable PPA.
https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable now has 1.1.10.

1. but as i said above, for next version (e.g. `1.1.11`) you (or me) would need to go to https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable and change Recipe (e.g. from `1.1.10` to `1.1.11`).
or you need to maintain a branch called "stable" that will point to latest commit of latest version (tag).
then i can configure ppa to make auto builds.

so it is either manual work in ppa or in git.

or you can modify https://github.com/pwr-Solaar/Solaar/blob/master/release.sh to update this "stable" branch automatically - this actually sounds like a best idea.

2. https://github.com/pwr-Solaar/Solaar/blob/master/tools/clean.sh is not needed anymore. it as used by https://github.com/muzena/Solaar/blob/python3-new1/packaging/debian/rules#L27 but it is not used by https://salsa.debian.org/debian/solaar/-/blob/debian/latest/debian/rules?ref_type=heads#L19 (it has its own cleaning command because that script was removed in 1.1.9)

3. please update links in https://launchpad.net/solaar-unifying :
"Home page" -> https://pwr-solaar.github.io/Solaar/
"External downloads" -> https://github.com/pwr-Solaar/Solaar/releases (or remove this link, not sure if it is useful)
i do not have permissions to do that.

4. daily build are not working at the moment because of issue i described in my previous comment.

**Comment by skitt** [comment]
> @skitt hi. while i was fixing ppa i have found a "future" issue with packaging. after [cf71736](https://github.com/pwr-Solaar/Solaar/commit/cf71736920ff85e9f5a082d3a7cfaadfc00af13d) commit your patch https://salsa.debian.org/debian/solaar/-/blob/debian/latest/debian/patches/skip-udev-rule-installation.patch?ref_type=heads does not work anymore. thus next version build will fail like this one - https://launchpadlibrarian.net/711847967/buildlog.txt.gz
> 
> i am not sure if it possible to fix packaging right now for future version and also have it backward compatible with current version.
> 
> maybe you can come out with some good solution for this issue before new release will be released. thanks.

That’s expected, and I have to go over the patches with every release — see the history on https://salsa.debian.org/debian/solaar/-/commits/debian/latest/debian/patches/skip-udev-rule-installation.patch?ref_type=heads

Obviously it causes problems for daily (or nightly, or per-commit) builds, I don’t have a nice solution for that.

Thanks for updating the PPA! I don’t have access either to update the solaar-unifying project information.

**Comment by antonsoroko** [comment]
@skitt sorry, in 2nd comment i meant to ping **pfps**. my bad.

>I don’t have a nice solution for that.

i see. sad. i thought that maybe it is possible create some universal patch or some logic about which patch to apply.

**Comment by antonsoroko** [comment]
@pfps  

0. I fixed stable PPA.
https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable now has 1.1.10.

(Initially i imported debian repo by myself, but then i found that ubuntu team [already imports debian repo we need](https://git.launchpad.net/ubuntu/+source/solaar/log/debian), so i just re-used it.)

1. but as i said above, for next version (e.g. `1.1.11`) you (or me) would need to go to https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable and change Recipe (e.g. from `1.1.10` to `1.1.11`).
or you need to maintain a branch called "stable" that will point to latest commit of latest version (tag).
then i can configure ppa to make auto builds.

so it is either manual work in ppa or in git.

or you can modify https://github.com/pwr-Solaar/Solaar/blob/master/release.sh to update this "stable" branch automatically - **this actually sounds like a best idea.**

2. https://github.com/pwr-Solaar/Solaar/blob/master/tools/clean.sh **is not needed anymore**. it as used by https://github.com/muzena/Solaar/blob/python3-new1/packaging/debian/rules#L27 but it is not used by https://salsa.debian.org/debian/solaar/-/blob/debian/latest/debian/rules?ref_type=heads#L19 (it has its own cleaning command because that script was removed in 1.1.9)

3. **please update** links in https://launchpad.net/solaar-unifying :
"Home page" -> https://pwr-solaar.github.io/Solaar/
"External downloads" -> https://github.com/pwr-Solaar/Solaar/releases (or remove this link, not sure if it is useful)
i do not have permissions to do that.

4. daily build are not working at the moment because of issue i described in my previous comment.

**Comment by antonsoroko** [comment]
@pfps for N1 i created https://github.com/pwr-Solaar/Solaar/pull/2236

**Comment by pfps** [comment]
@antonsoroko Thanks.  

I'll leave clean.sh around for now just in case.

What's the process for editing the launchpad page for Solaar?  Or I can just make you an administrator.

I'll work on setting up the stable branch.

What's the problem with the daily builds?  Is it that whenever Solaar gets a new dependency the build recipe has to be updated?

**Comment by pfps** [comment]
Version 1.1.11 will go out after the current code PRs are tested and maybe one more feature is added.

**Comment by antonsoroko** [comment]
1.
>I'll leave clean.sh around for now just in case.

What I meant is that i am not sure if this script is up to date with latest changes of app code. If this script can be updated to do proper clean after building a release - then it can be used again in any packaging (not only for Debian). After update of this script you can notify **skitt** so he can update Debian scripts (link to specific code is above if you are interested).

2.
>What's the process for editing the launchpad page for Solaar? Or I can just make you an administrator.

I do not know :-) I guess there should be "edit" button. But if even you do not see it, then maybe only gogo can update that page.

3.
>I'll look at the stable branch PR.

Thanks.

Btw, it is good to know how to edit ppa recipes anyway:
a. https://launchpad.net/~solaar-unifying
b. "Code" tab
c. "Source package recipes" link
d. open recipe
e. at very bottom of page there is code of recipe and edit button
example
https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable
![image](https://github.com/pwr-Solaar/Solaar/assets/17964763/71cc70de-1f32-47e3-89da-cdd4f0d13dbd)

https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-git
![image](https://github.com/pwr-Solaar/Solaar/assets/17964763/bf199a78-ad16-4cba-9ecf-cfdc16fa231d)

f. note that "Request build(s)" button - it is used to make build. Since stable ppa uses specific tag - it has "Build schedule: Built on request". (Unstable ppa uses daily build since it uses master). So you need to click this button after changing tag to trigger new build. This is for stable ppa only, of course. And only if my idea with "stable" branch will fail. So it is just a "knowledge sharing".

4.
>What's the problem with the daily builds? Is it that whenever Solaar gets a new dependency the build recipe has to be updated?

about dependency - yes. but this is different.

in debian the correct way to distribute udev rules is via special helper. but in solaar you use setup.py.
thus **skitt** created a patch that removes installation of udev rule from setup.py. but after https://github.com/pwr-Solaar/Solaar/commit/cf71736920ff85e9f5a082d3a7cfaadfc00af13d his patch will not work anymore (b/c path uses specific string and this string was changed.)

i wrote technical details here https://github.com/pwr-Solaar/Solaar/issues/2186#issuecomment-1917467481

**Comment by antonsoroko** [comment]
@skitt 
>That’s expected, and I have to go over the patches with every release 

I think the good solution would be to use same tags approach as in upstream repo.
As i can see, in your repo you also created versions tags.
So each your tag can have correct packaging for each upstream repo tag. (by correct i mean proper patches and dependencies and etc for specific solaar version.)
And then in `debian/latest` you can have packaging for latest upstream code. and when time will come - you will just create new tag from this `debian/latest` branch.
Also, you can create `stable` branch that will point to latest release tag - the same way we are going to do in https://github.com/pwr-Solaar/Solaar/pull/2236. so stable can be used for build systems that can not work dynamically with tags (like ppa) - in case if the system that Debian use can not work with tags.

Unfortunately i am not familiar with build system that debian uses to build packages from source repos.
But even if this system can not use tags - it can use this new `stable` branch for stable releases and `debian/latest` for unstable.

What do you think?

**Comment by pfps** [comment]
> > I'll leave clean.sh around for now just in case.
> 
> What I meant is that i am not sure if this script is up to date with latest changes of app code. If this script can be updated to do proper clean after building a release - then it can be used again in any packaging (not only for Debian). After update of this script you can notify **skitt** so he can update Debian scripts (link to specific code is above if you are interested).

clean.sh appears to be doing reasonable things.   It does clear out the directory that distributes the translations, which requires compiling them afterwards.   This is probably reasonable.

> > What's the process for editing the launchpad page for Solaar? Or I can just make you an administrator.
> 
> I do not know :-) I guess there should be "edit" button. But if even you do not see it, then maybe only gogo can update that page.

I'll dig some more.

> > What's the problem with the daily builds? Is it that whenever Solaar gets a new dependency the build recipe has to be updated?
> 
> about dependency - yes. but this is different.
> 
> in debian the correct way to distribute udev rules is via special helper. but in solaar you use setup.py. thus **skitt** created a patch that removes installation of udev rule from setup.py. but after [cf71736](https://github.com/pwr-Solaar/Solaar/commit/cf71736920ff85e9f5a082d3a7cfaadfc00af13d) his patch will not work anymore (b/c path uses specific string and this string was changed.)
> 
> i wrote technical details here [#2186 (comment)](https://github.com/pwr-Solaar/Solaar/issues/2186#issuecomment-1917467481)

OK

**Comment by skitt** [comment]
> > That’s expected, and I have to go over the patches with every release
> 
> I think the good solution would be to use same tags approach as in upstream repo. As i can see, in your repo you also created versions tags. So each your tag can have correct packaging for each upstream repo tag. (by correct i mean proper patches and dependencies and etc for specific solaar version.) And then in `debian/latest` you can have packaging for latest upstream code. and when time will come - you will just create new tag from this `debian/latest` branch. Also, you can create `stable` branch that will point to latest release tag - the same way we are going to do in #2236. so stable can be used for build systems that can not work dynamically with tags (like ppa) - in case if the system that Debian use can not work with tags.

I appreciate the time you’ve spent thinking about this; I should have made this clearer, all this isn’t a problem that needs fixing.

For most projects, Debian doesn’t care about individual commits, only about releases. And because Debian cares a lot about the licensing and provenance of all the files it publishes, most projects don’t have automated imports from upstream. Debian packages aren’t built automatically from a VCS, they are built from source packages which are manually uploaded by maintainers. There is work ongoing to change that, but that’s the current situation.

So when a project (like Solaar) publishes a new release, the maintainer imports it (for Solaar, only the release tarball; some projects import the full git history, but that requires — in theory — auditing every single commit rather than just the release), and adjusts the packaging as required. It _is_ possible to do that more frequently than at a release cadence (see for example [`sdl2-compat`](https://tracker.debian.org/pkg/sdl2-compat) or [binutils](https://tracker.debian.org/pkg/binutils)), but doing it for every commit isn’t scalable; in particular, if you try that you often end up dealing with temporary breakage upstream, and you often make changes that have to be undone.

For the particular patch you’re concerned about, dealing with it when the next release of Solaar is imported into Debian is pretty trivial. There is a better fix, which would be to rely on the `udev` `pkg-config` module: `pkg-config --variable=udevdir udev` gives the correct target directory for the system.

**Comment by pfps** [comment]
@antonsoroko Have you looked at the daily build recipe?

**Comment by antonsoroko** [comment]
@skitt 
>For the particular patch you’re concerned about, dealing with it when the next release of Solaar is imported into Debian is pretty trivial. 

I understand that. But this also means that it is not possible to build and "unstable" build until new version will be released and you will make a new patch. that's why i wrote my thoughts about this situation.
I did not mean to update code from upstream in Salsa every time, i just meant to create a branch that will have only necessary ongoing packaging changes for next release. So it can be used for so called "daily builds" and after final release it also can be quickly used for this new release.

But if you do not see value in such branch with ongoing packaging changes - then ok. I guess this activity can take extra time that can be used in a better way. We can simply wait for version 1.1.11. I do not expect that those daily builds are used by many people (if any).

(I do not think anyone want to duplicate the work about packaging thus I just want to re-use your scripts and I appreciate that you maintain them.)

**Comment by antonsoroko** [comment]
@pfps yes of course. i changed it for future but as i wrote above it will not work right now. daily builds will work after 1.1.11 release will be released and skitt will make changes in his repo.
or if we will fork his changes and make some edits. but then it is duplication of work.

**Comment by pfps** [comment]
OK.  1.1.11 should be out soon and we can see what works then.

**Comment by antonsoroko** [comment]
@skitt Just to be clear: stable ppa build for 1.1.11 will not work immediately after you make a release. it will work when debian repo will be updated. i mean: launchpad will detect changes in your repo and will try to build, but since debian scripts are not updated yet - it will fail. then then debian repo will be updated - launchpad will detect changes in it and try to make a build again - this time build should succeed.

As i mentioned above, the main issue here is absence of parity between your repo and debian repo. since these 2 repos are managed by different people - there always will be time lag if new release has "breaking changes" (like new dependency or change of code that should be patches for debian by scripts, like the situation we have now) for packing scripts. for stable release this lag will be small i guess, for unstable - can be until next version (because debian scripts are updated when new version is released).

And this situation can not be fixed as i can see: Solaar team do not want to maintain debian packaging scripts and debian maintainer do not want constantly monitor this repo for changes. This is not about blaming someone, it is just fact of life. I do understand position of both parties :-)
So we just should adjust our expectations correspondingly. 

To be honest - i am not sure if this unstable ppa is even needed. we can keep it if you want. the only bad things about it - it generates email about every failed builds :-) 

When new stable version is released and it failed to build - then i guess we can ping skitt to make a fix. But for unstable - it would be impolite/annoying i guess.

**Comment by pfps** [comment]
The Ubuntu daily (git) PPA has proved to be useful, but if it becomes too difficult to maintain then there is no real reason to keep it.   Historically, it has needed maintenance whenever Solaar acquires a new dependency, which isn't often.

**Comment by pfps** [comment]
The Ubuntu package home page can only be changed by the owner, who hasn't been responsive.   I've started a process to document non-responsiveness which should eventually allow updating the home page.

**Comment by antonsoroko** [comment]
>The Ubuntu daily (git) PPA has proved to be useful

then we can keep it.

>Historically, it has needed maintenance whenever Solaar acquires a new dependency, which isn't often.

this will remain the same with only difference that packaging repo is now belongs to different person (debian maintainer instead of gogo).

if it would be needed, in future we can fork debian repo and then we can make more prompt changes there. although this sounds like a duplication of work, this still can be done. i guess gogo used that approach but then dropped it.

**Comment by pfps** [comment]
@skitt @antonsoroko 
I just made release 1.1.11rc1

If you want to test out something related to a release you can use this pre-release.

If there are no problems release 1.1.11 will go out in about a week.

**Comment by pfps** [comment]
@antonsoroko I just made release 1.1.11 and it is the tip of the stable branch.

**Comment by antonsoroko** [comment]
@pfps 
looks like skitt already made packaging changes https://salsa.debian.org/debian/solaar/-/commits/debian/latest/debian?ref_type=heads
but ubuntu repo has not imported those changes yet
https://code.launchpad.net/~git-ubuntu-import/ubuntu/+source/solaar/+git/solaar

at the moment it is not clear to me how they do import and how they match debian git repo branches to ubuntu branches, so let's wait and see.

**Comment by antonsoroko** [comment]
@pfps 

1. i have no idea about the logic how ubuntu team updates their mirror of skitt repo.
so i decided to use our own mirror: https://code.launchpad.net/~solaar-unifying/solaar-unifying/+git/debian-packaging
so, "stable ppa" works https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable
version 1.11 is available for all modern versions of Ubuntu. 
see configuration here https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable

2. "git ppa" broke almost immediately after release of 1.11, because of this commit
https://github.com/pwr-Solaar/Solaar/commit/7774569971279cc048faa51057dc570993b0e2c0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
so i disabled auto builds.

3. also unittests are failing for some reason for new builds. see the end of https://launchpadlibrarian.net/716180342/buildlog_ubuntu-mantic-amd64.solaar_1.1.11+git2155-ce00a78e~ubuntu23.10.1_BUILDING.txt.gz It is not critical for building, so this is just an information.

4. imho, "git ppa" makes zero sense without your own packaging scripts where you can change them immediately after you introduced breaking changes. as i wrote above, i disabled it, in future you can enable it back here https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-git (note that if it is failing - it will generate email about every failed build for every ubuntu version, every day if that day has commits)

**Comment by pfps** [comment]
I've only been involved here to create some sort of continuity.  If you feel that it is not worthwhile to have the git PPA then I'll remove it from the Solaar information.

**Comment by antonsoroko** [comment]
@pfps if i understood correctly - your team do not have plans to include packaging code from skitt repo into your repo, or to create a fork of his repo under pwr-Solaar organisation (and, regardless of copying approach, maintain that code) - thus i do not see value in this "git ppa". "git ppa" should be monitored and updated when needed. personally i do not want to monitor that ppa. stable ppa has more value and needs less attention.
so i vote for "remove it from the Solaar information."
thank you.

**Comment by pfps** [comment]
OK.  I've removed pointers to the git PPA.

**Comment by pfps** [comment]
Should we  close this issue?

**Comment by antonsoroko** [comment]
i think it can be closed.
of course we can wait for new version to test this process again, but i think the process will not change: you make release, skitt make changes to packaging for Debian users, and then PPA build packages for Ubuntu users.

**Comment by pfps** [comment]
In any case this issue can be reopened if necessary.
