### ISSUE TITLE
No FN toggle for K830

### ISSUE THREAD

**Issue by vdvogt** [pwr-Solaar/Solaar#248]
Hi,
I just installed solaar on my Debian 8 system with a K830 kb.
But there is no FN toggle!

What went wrong?

Veit

**Comment by tsaber** [comment]
same here with a k400 kb. I see the button but when I click on Swap Fx function it says Read/write operation failed.
![logite](https://cloud.githubusercontent.com/assets/9378902/11897588/280d908a-a591-11e5-993e-804251fc5702.jpg)

**Comment by nfultz** [comment]
From the CLI v 0.9.2, I get this:
```
solaar-cli: error: no settings for Illuminated Living-Room Keyboard K830
```

It would be nice to have fn keys supported.

**Comment by trinitronx** [comment]
@nfultz :  Just got a new K780 and installed `solaar` and `solaar-gnome3` packages on Ubuntu 18.04.  It appeared to detect my device but didn't show supported HID options such as `fn-swap`.

Looking in this source repo for issues & pull requests, I discovered that the latest code here does support my K780 device.  However, the package in Ubuntu / Debian is out of date although they both say they are `v0.9.2`.

You probably have the same issue.  I did a quick check for your device and found that latest code in this repo on `master` branch supports K830:

```
:~$ grep -rin K830  /usr/local/lib/python2.7/dist-packages/
Binary file /usr/local/lib/python2.7/dist-packages/logitech_receiver/descriptors.pyc matches
/usr/local/lib/python2.7/dist-packages/logitech_receiver/descriptors.py:218:_D('Illuminated Living-Room Keyboard K830', protocol=2.0, wpid='4032',
:~$ grep -rin K830  /usr/local/lib/python2.7/dist-packages/logitech_receiver/descriptors.py
218:_D('Illuminated Living-Room Keyboard K830', protocol=2.0, wpid='4032',
:~$ grep -rin K830 /usr/share/solaar/lib/logitech_receiver/descriptors.py
:~$ dpkg -L solaar | grep -i descriptors.py 
/usr/share/solaar/lib/logitech_receiver/descriptors.py
:~$ dpkg -l solaar
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-==================================================================================================
ii  solaar                                         0.9.2+dfsg-8                 all                          Logitech Unifying Receiver peripherals manager for Linux
:~$ which solaar 
/usr/local/bin/solaar
:~$ solaar --version
solaar 0.9.2
:~$ dpkg -L solaar | grep -i bin
/usr/bin
/usr/bin/solaar
/usr/bin/solaar-cli
:~$ /usr/bin/solaar --version
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
solaar 0.9.2
```

As you can see, I have 2 separate versions of `solaar` installed on my system.  One is from the `.deb` package and is installed in `/usr/bin/solaar`.  The other I used `--prefix /usr/local` to install and it lives under `/usr/local/bin/solaar`.

Due to the search `$PATH` in bash and POSIX shell, the later version I installed in `/usr/local` takes precedence and so they can happily live on the same system although I'm using the later version.  This is an old Unix / Linux trick and is used in a mostly standard fashion to install user packages under `/usr/local`.  Python has the same concept with `site-packages` directory under it's directory structure.

So you might try installing this later version like I did:

```
git clone git@github.com:pwr/Solaar.git 
cd Solaar
./rules.d/install.sh
sudo python setup.py install --prefix /usr/local  --install-layout deb 
```

Don't forget to unplug your Unifying Receiver USB dongle so the new `udev` rules you just installed will change ownership of the `/dev/hidraw*` device to group `plugdev`.  Also make sure your user is in this `plugdev` group to have permissions to access this device.  Check the [`installation.md`][1] file in this repo for details.

[1]: https://github.com/pwr/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Please clone the version of Solaar in this repository and run
bin/solaar show 
from there when the mouse is on and active.
I can look at the output and see what the mouse can do.

**Comment by nfultz** [comment]
I'll try again once I update to ubuntu 20.04 and get a newer release of solaar.

**Comment by pfps** [comment]
You should be able to try out solaar from this repository simply by cloning this repository and running bin/solaar from it.

**Comment by nfultz** [comment]
I tried running it from a clone, but I see `Solaar: missing required package 'python-gi'`

**Comment by FFY00** [comment]
Install that package.

**Comment by nfultz** [comment]
```$pip install python-gi
ERROR: Could not find a version that satisfies the requirement python-gi (from versions: none)
ERROR: No matching distribution found for python-gi
```

**Comment by pfps** [comment]
That's a system package not a python package.  You should install it using apt, and the package is python3-gi.

But it's my fault for not asking you to look at the installation document.  I run Fedora and most of the system packages for Python 3 and GTK are installed by default so I sometimes forget that this needs to be done.

@FFY00 Should the package names in gtk.py be changed to their python3 versions in the calls to _require?

**Comment by FFY00** [comment]
> @FFY00 Should the package names in gtk.py be changed to their python3 versions in the calls to _require?

Where?

**Comment by pfps** [comment]
@FFY00 Oops.  In gtk.py.  The function _require has an extra argument that is just used in the error message.

**Comment by pfps** [comment]
I'm closing this issue as likely not a problem in the current version.
If it is still a problem, please comment here and the issue can be reopened.

**Comment by nfultz** [comment]
Just wanted to add that this is now working in Ubuntu 20.04 for K830, although the FN toggle seems to be backwards / inverted. Thanks!
