### ISSUE TITLE
Lost scroll , open label:"help wanted" 

### ISSUE THREAD

**Issue by mirrortorrent** [pwr-Solaar/Solaar#2516]
**Information**

- Solaar version (`1.1.13 --version` and `"help wanted"  --tags`):
- Distribution:
- Kernel version (ex. `ubuntu 22.04.4 LTS -6.5.0-35 generic`):
- Output of `solaar show` for the target device (if applicable):

<details>

```

```
</details>

**Is your feature request related to a problem? Please describe.**

"help wanted" 
(don't think I have ever done a post on GitHub so if this is not the right places... Sorry I am new to this)
I have a MX Master 3S and for what ever thing I have done I have  lost all scroll and I want it back. How would I do that?

my second issue is how to set up rules? thanks for your help.

**Comment by pfps** [comment]
"lost all scroll" isn't very specific.   If you want help you will have to describe exactly what the problem is.

If you think Solaar is involved the first thing to do is to quit out of Solaar and then turn your mouse off and on again.  That will remove all influence of Solaar.   If the problem persists then Solaar is not involved.

I expect, though, that your scrolling is just very slow.   This may be caused by the Linux input driver using high-resolution scrolling but Solaar setting the mouse to low resolution.  The solution is to set the Scroll Wheel Resolution setting to ignore in Solaar by clicking on the lock icon until it changes to a do-not-enter icon.

**Comment by mirrortorrent** [comment]
Thank you for the reply it was very helpful and yes very inconsiderate just say "scroll stop" I should have given some correlations.

"If you think Solaar is involved the first thing to do is to quit out of Solaar and then turn your mouse off and on again. That will remove all influence of Solaar. If the problem persists then Solaar is not involved."  

this is spot on and what I need to keep most of the functionality. Okay you are very right . I am very happy with the default Linux drivers even the thumb wheel works left to right and I can use that. Now I would like to put the three other buttons to work how do I program those? Thanks

**Comment by pfps** [comment]
There are seven buttons on the mouse.  Six of them should perform useful functions under Linux without any involvement of Solaar.  I suggest reading the Logitech documentation for the mouse, such as https://support.logi.com/hc/en-us/articles/5218056588311-Getting-Started-MX-Master-3S

**Comment by pfps** [comment]
Closing due to no response from submitter.
