### ISSUE TITLE
Target the same device with different connection modes (Bluetooth vs Bolt)

### ISSUE THREAD

**Issue by immanuelfodor** [pwr-Solaar/Solaar#2533]
Can I somehow target the same device with different connection modes to build up matching rules for setting the scroll resolution? 

When my MX Master 3S is connected to the bolt receiver, the default "Scroll Wheel Resolution" `false` is the right option. But when it's connected via Bluetooth, this setting needs to be turned to `true`. If left false, scrolling is almost impossible; you need to spin the wheel so much to get just a little scroll. Turning it to true achieves the same scroll experience as normally expected when scrolling with the bolt receiver or on any other regular mouse. 

Within the rule editor, the mouse is visible with the same ID no matter the connection type, so I can't use a "Device" condition as of now.

Ideas: The device path seems different - `/dev/hidraw6` for the bolt receiver and `/dev/hidraw0` for the BT-connected mouse. Can I leverage this somehow in a rule? Or any better solutions? 

![image](https://github.com/pwr-Solaar/Solaar/assets/21174107/4c037b0a-46ea-40ed-ac7b-b7b4b22e41af)

**Comment by pfps** [comment]
Solaar doesn't have this ability and is not likely to.   Devices are supposed to work the same no matter how they are connected.

What is likely happening is that the Linux input system recognizes the device as supporting smooth scrolling only when it is connected via Bluetooth.

The solution is to have the Scroll Wheel Resolution set to ignore so that Solaar will not interfere with it.   Then the drivers can do whatever they want to do.

If that doesn't work the error is in the interaction between the drivers and the device and the solution is to have the drivers fixed.

**Comment by immanuelfodor** [comment]
Thank you so much! I didn't know about ignore, but setting it now helped.
Scroll works fine in both connection modes now :hugs: 

![image](https://github.com/pwr-Solaar/Solaar/assets/21174107/ccdb6089-f626-46c4-998e-782b060c41bc)
