### ISSUE TITLE
Solaar should have a UI option to start hidden (only in tray)

### ISSUE THREAD

**Issue by rgpublic** [pwr-Solaar/Solaar#2633]
If I add Solaar via Gnome Tweaks as a startup application, I cannot add any command line arguments like "--window=hide". I can edit the desktop file in /usr/share/applications, but I don't think that's a very user-friendly option. In my opinion there should be a settings screen with at least the option "[x] Don't open on startup" and perhaps even "[x] Load on startup" so users won't have to go through Gnome Tweaks at all. Thank you for making Solaar :-)

**Comment by pfps** [comment]
Solaar is maintained by a small team.   This enhancement is not currently a priority and likely will not be implemented soon, or maybe even ever, unless someone new does the programming.

**Comment by MattHag** [comment]
We could add an environment variable just for the window option, if that helps. That seems doable.

**Comment by rloutrel** [comment]
@rgpublic : Ia ma using solaar on Gnome (Ubuntu)

This is my startup option, and it starts minimized
![image](https://github.com/user-attachments/assets/2df2f96c-24da-4f4f-853a-e6a33752624a)

**Comment by rgpublic** [comment]
Well, thank you everyone for your help. See my original issue description though. I know about the command line options and I've solved it for now by adding --window=hide. I might be wrong but an environment variable would probably be much of an improvement. I just thought a settings screen where I could simply change this option directly in the application would be better - many other applications have this and that's what this issue is about, but I totally understand that it's too much work for now - no problem. Thanks again for your answers anyway. :sunflower:

@rloutrel :  
When I open Gnome tweaks and go to "Start up applications" there's no way to edit it via UI btw...:

![image](https://github.com/user-attachments/assets/e0be0913-cc2e-432d-805d-dbcac9b36e19)

**Comment by rloutrel** [comment]
Do not access to the startup application via tweaks, but the startup application tools. Then you will be able to edit the call:
![image](https://github.com/user-attachments/assets/4b86f906-68fa-4893-b8b6-c78b65a7cfbd)

then:
![image](https://github.com/user-attachments/assets/50eed00a-5ba2-4468-8046-5e8c70568bfb)

**Comment by rloutrel** [comment]
@MattHag : 

- Is [this](https://github.com/rloutrel/Solaar/tree/feature/menu) visually what you mean (not binded yet)?

@pfps / @MattHag :
- Is there a configuration file where to save? How to access it from the window.py file
- My implementation would be something like:
  - if parameter -w / --window is used, the option is shown (checked if value is hide) as disabled with a mouse over text, saying that the option is set as command line argument (to avoid conflicts and make it clear to the user, where the option is set)
  - otherwise, the value is saved in the configuration file
  - at startup, in solaar/gtk.py, if -w/--window is not set , read the value from configuration file (default = False) here:
```  
    if args.window is None:
        args.window = "show"  # default behaviour is to show main window
```
