### ISSUE TITLE
how to reprog FN-Key on K800

### ISSUE THREAD

**Issue by TheRojam** [pwr-Solaar/Solaar#306]
How to reprogramm the FN on K800?
I didnt find more Information about this?

**Comment by Lekensteyn** [comment]
The original devices using HID++ 1.0 are supposed to be programmable via the GUI (or CLI). Maybe you got a newer version. What is the output of `solaar show`?

**Comment by TheRojam** [comment]
`
usage: solaar [-h] [-d] [-V]
solaar: error: unrecognized arguments: show
`
F1 open a tab with the startpage in FF.
I want to set the key to different commands

**Comment by jrbenito** [comment]
@TheRojam ,

You might be using solaar version provided by your distribution packet manager (.deb or .rpm) right?

In this case you need to run `solaar-cli show'.

Also, please, if you can download latest version from this repository and try we would appreciate. In order to do this, quit solaar, open a terminal and type:

```
$ mkdir Solaar
$ cd Solaar
$ git clone https://github.com/pwr/Solaar.git 
```
(or you can download and unzip the [zip package](https://github.com/pwr/Solaar/archive/master.zip))
```
$ ./bin/solaar show 
```

Please report results.

thanks

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
