### ISSUE TITLE
missing feature - thumb button - m705

### ISSUE THREAD

**Issue by TheRojam** [pwr-Solaar/Solaar#307]
If I use the thumb button on my M705 it dies have the same like on macOS named [MissionControl](https://support.apple.com/en-us/HT204100). May you can add a feature like this re can explain how to add it to my openbox/archLinux Setup.

**Comment by Petross404** [comment]
Solaar could also make use of libinput in order to adjust and configure button mapping and/or command launch with some rarely used mouse-buttons.

**Comment by Lekensteyn** [comment]
Can you clarify what you are looking for? What is currently happening and what would you like to see instead?

**Comment by Petross404** [comment]
What I am refering to, is that solaar should act also as a fronted to libinput or xmodmap, in order to re-map some of it's buttons. Let's say that I want my middle click to be the thumb button (Zoom in MX Perfomance) or that another button should start a terminal etc.

Especially under Wayland compositors, that xmodmap isn't working and libinput configuration is kinda difficult, it would be so nice and convenient if Solaar could configure the mouse.

**Comment by TheRojam** [comment]
@Lekensteyn I want to have to see all my opend windows on the desktop i am working on, like in ![MissionControl.](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/el_capitan-mission_control.png) Mission Control.
See the Picture above to see whats happend by using the thumb (unvisible) button.
_You didn't read the mentioned link from Apple Documentation?_

**Comment by Lekensteyn** [comment]
@TheRojam I did check the link, but was not sure what you change you would like to see in Solaar. (is "dies" also a typo for "does"?)

Is my understanding correct that you would like the remapping functionality that is described by @Petross404 ? At the moment (due to lack of resources (time)), such a feature will not be added anytime soon to Solaar.

**Comment by pfps** [comment]
Closing as out of scope
