### ISSUE TITLE
MX Master no avaliable settings

### ISSUE THREAD

**Issue by Tomaszal** [pwr-Solaar/Solaar#321]
Not sure if this is just how this should work, but going from this file ([Solaar/docs/devices/mx-master.txt](https://github.com/pwr/Solaar/blob/0b8141f0928b173a36b6c7d27a948538b0730d52/docs/devices/mx-master.txt)) MX Master mice should have more than 0 options.
I'd be glad to hear any information on this :)

solaar-cli show
Unifying Receiver [/dev/hidraw0:80099929] with 2 devices
1: Wireless Mouse MX Master [MX Master:040318B6]
2: Wireless Keyboard K360 [K360:C6BE58C4]

solaar-cli config 1
solaar-cli: error: no settings for Wireless Mouse MX Master

Index        : 1
Wireless PID : 4041
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial       : 040318B6
  Bootloader : BOT 18.01.B0014
  Firmware   : MPM 11.02.B0014
  Firmware   : MPM 11.02.B0014
  Other      : 

Edit: forgot to add that I'm installing it on Arch from user repository.

**Comment by Lekensteyn** [comment]
Is the device powered on?

"solaar-cli" is the older program I think, try installing solaar-git instead of solaar.

**Comment by Tomaszal** [comment]
Yes, it is. "solar-git" package works as I expected though, so thanks!

I've got one question though. Is it possible to reconfigure the small button on top so it doesn't trigger the freespin mode? Because essentially right now that button is being wasted and could be ideally used for something else.

**Comment by Lekensteyn** [comment]
@javitonino do you know whether the button is remappable? Maybe this could help:

https://lekensteyn.nl/files/logitech/x1b04_specialkeysmsebuttons.html

**Comment by javitonino** [comment]
Yes, it's remappable (as are all buttons on the mouse), but AFAIK there is no support in Solaar for button remapping in general.

Not sure if this can be implemented purely in Solaar, since I think remapped events go through HID++ and are not picked up by the kernel (which only speaks HID). In fact, if you reprogram the mouse buttons in Windows using a VM and then come back to Linux, the buttons don't work until you reset the mouse. I'll try to do some digging if I get the time.

**Comment by Tomaszal** [comment]
Would be glad to give any help if testing needs to be done. Would be amazing to get this thing working properly on Linux!

**Comment by javitonino** [comment]
I've been taking a look at remapping options. The remapping controls work as indicated in the spec posted by @Lekensteyn (thanks!). There are two options on how to remap controls: you can either remap to another mouse button, or you can "divert" the button. which causes the button presses to be reported via HID++, instead of HID. This is what the Windows drivers do, but as Linux doesn't recognize HID++ events, those are lost.

However, remapping the buttons works fine on Linux, for example, by using the following commands (using the HID console shipped with Solaar, and assuming the Reprogrammable Controls features is mapped to slot 08):
`11 01 083D 00C4 02 0052`
This remaps the smart shift button (00C4) to the middle mouse (0052). This is the lists of mappable buttons:
- `0050`: Left click
- `0051`: Right click
- `0052`: Middle (wheel) click
- `0053`: Back
- `0056`: Forward
- `00C3`: Gestures (HID++)
- `00C4`: Smart shift (HID++)

So there is not much choice for remapping, only 5 buttons can be read by Linux HID stack, and those are already present in the mouse, so I can see no easy way to squeeze some extra buttons out of the mouse.

I ran a brute-force search (loop over 65k possible combinations, see which remappings do not produce an error) and could not find any more viable candidates.

**Comment by Lekensteyn** [comment]
Diverting it to HID++ would require modifications to the Linux hid-logitech-hidpp kernel driver. (You really do not want such input processing in Solaar for reliability/performance reasons.)

**Comment by AcerLaurinum** [comment]
@javitonino Thanks so much for the instructions on remapping the controls. For some reason every time I shutdown my computer the remapping is reset and I have to do it over again. Is there something I can do to ensure the remapping gets saved?

**Comment by Jezza** [comment]
Yeah, I'm in the same position.
I have a MX Master 2S, and I see nothing but the battery status, and the wireless link.

**Comment by Jezza** [comment]
Oh, nevermind.
I was still running the older version.

The latest on master definitely fixes it.

**Comment by benyanke** [comment]
I have the MX Master 2S as well - is there going to be a release from master that fixes this?

**Comment by jstrzebonski** [comment]
> (...)
> 
> However, remapping the buttons works fine on Linux, for example, by using the following commands (using the HID console shipped with Solaar, and assuming the Reprogrammable Controls features is mapped to slot 08):
> `11 01 083D 00C4 02 0052`
> (...)

@javitonino 

Could you explain how did you come up with that command? Especially `083D` and `02` between `00C4` and `0052`?

Thanks!

**Comment by witheld9** [comment]
Sorry nevermind I got it, 11 03 0A3D 00C4 02 0052

**Comment by pfps** [comment]
Remapping in the UI might be coming, stay tuned.

**Comment by pfps** [comment]
The MX Master should be supported in the current version of Solaar from this repository.  If you are still having problems please clone this repository and run bin/solaar from the download directory.

**Comment by pfps** [comment]
Closing due to no response from reporter.
