### ISSUE TITLE
Incorrectly commiting DPI value to config.json

### ISSUE THREAD

**Issue by simokron** [pwr-Solaar/Solaar#328]
Hi,

Let me just start off by saying that I really appreciate your work, Solaar is quite frankly a necessity for anyone using  a Logitech peripheral.

Alright, onto the issue: I believe that Solaar incorrectly writes the dpi information in its config file (that is `~/.config/solaar/config.json`). The auto-generated version looks like this:

```javascript
{
  "4041:ADFAA385": {
    "_name": "Wireless Mouse MX Master",
    "dpi": "1600",
    "smart-shift": 50
  },
  "_version": "0.9.2"
}
```

Note the quotation marks around the dpi value but not around the value for smart-shift. I had an issue whereby Solaar didn't apply the dpi settings on device wake, but removing these quotation marks made it work.

This is using a freshly built version from GitHub, by the way (specifically the `solaar-git` package from the Arch AUR).

Thanks,

**Comment by Lekensteyn** [comment]
I guess that the problem is that `_feature_adjustable_dpi_choices` returns a `NamedInts` mapping from ints to string. These are subsequently used by `feature_choices_dynamic` which calls `feature_choices` which calls `ChoicesValidator`.

That validator indeed expects a NamedInts instance. Do you have a fuller stack trace of where it goes wrong? I think it will complain here:

	def prepare_write(self, new_value, current_value=None):
		if new_value is None:
			choice = self.choices[:][0]
		else:
			if isinstance(new_value, int):
				choice = self.choices[new_value]
			elif new_value in self.choices:
				choice = self.choices[new_value]
				^^^ "new_value" is a string, but "NamedInts" maps from ints, not from string.

Possible solution is to use add a case:

    elif int(new_value) in self.choices:
        choice = self.choices[int(new_value)

did not look further at what could go wrong though.
