### ISSUE TITLE
failed to open pairing lock

### ISSUE THREAD

**Issue by nex86** [pwr-Solaar/Solaar#403]
What does this mean?

I'm trying to use this on my Raspberry pi using the latest version of Raspbian.

**Comment by pfps** [comment]
There are several possible causes.
If you have a unifying receiver (one with the star logo) then there are already six paired devices and one has to be unpaired first.  I just put in some changes to not allow pairing in the UI if this is the case.
If you have a nano receiver (with the star logo) then the receiver is probably out of pairing attempts.  I have some changes in the works to show how many pairing attempts are left.
Otherwise try with the current version of solaar from this repository and report back if you are sitll having problems.

**Comment by pfps** [comment]
Closing due to no response from original poster.
