### ISSUE TITLE
M305 nano receiver 046d:c52f unpairing failed

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [pwr-Solaar/Solaar#406]
>Failed to unpair Wireless Mouse M305 from Nano Receiver
>The receiver returned an error, with no further details

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

$ apt-cache policy solaar
solaar:
  Installed: 0.9.2+dfsg-

**Comment by jkldgoefgkljefogeg** [comment]
I was trying to pair the receiver with a different mouse. I tried `Pair new device` under nano receiver, got
>Pairing failed: failed to open pairing lock. No futher details are avilable about the error.

But the mouse started working
>hid-generic 0003:046D:C52F.0006: input,hiddev0,hidraw1: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-3/input1

**Comment by pfps** [comment]
Nano receivers work differently and are not currently handled completely correctly in Solaar.  I have some fixes in the works so stay tuned if you still care.

**Comment by pfps** [comment]
@jkldgoefgkljefogeg It appears that this receiver pairs by replacing existing pairings.  I have some changes almost ready for Solaar for a similar receiver.   If you are still using Solaar could you post output from solaar show while the receiver is plugged in?  I can then maybe describe this receiver in Solaar so that it is handled correctly.
