### ISSUE TITLE
new release plans?

### ISSUE THREAD

**Issue by keradus** [pwr-Solaar/Solaar#407]
Hi !
Great software ;)

Are you planning any new release? quite a lot work since last one: 
https://github.com/pwr/Solaar/compare/0.9.2...master

**Comment by cement-head** [comment]
I have the following:

```
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 001 Device 003: ID 04f2:b59d Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 8087:0a2b Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

And I have the M185 Logitech Mouse, but it's not recognised.

Any hope of getting this fixed for Xenial (16.04) and/or 18.04?

Thanks,
Andor

**Comment by keradus** [comment]
@cement-head , it looks like support for it was added (https://github.com/pwr/Solaar/pull/337), yet not released

**Comment by cement-head** [comment]
Any idea when the M185/nano receiver will get rolled into the deb?

**Comment by cement-head** [comment]
Okay, the most recent build from GIT (installed manually) works pretty well.

![screenshot from 2018-01-12 06-14-28](https://user-images.githubusercontent.com/1056700/34872760-39a89f10-f760-11e7-8495-063ca7e40a53.png)

**Comment by cement-head** [comment]
Need battery work, but the new type nano/unifying receiver works.

**Comment by doctor64** [comment]
@cement-head According to your screenshot, you have M185 "new version", which does not report battery status. You can verify under windows, using Logitech software. See https://github.com/pwr/Solaar/pull/337#issuecomment-288398793

**Comment by cement-head** [comment]
Okay, had to install devscripts and then it built.

Here's a GoogleDrive URL for the Ubuntu builds: https://drive.google.com/drive/folders/1lUJ6omeYNnPfhydCL1jYpBNTYLfY_mip

How can I upload to git hub?

**Comment by Petross404** [comment]
Any news on whether or not there will be a new release? I want to update it for the gentoo portage tree.

**Comment by Lekensteyn** [comment]
@Petross404 There will be a new release, but there is no date yet. First all existing PRs and some issues should be reviewed and then some tests has to be done.

**Comment by keradus** [comment]
that sounds promising ;)
what about making 2 releases? one with what is already merged, one with PRs that will be merged in future ?

**Comment by Lekensteyn** [comment]
Ok, perhaps at least it should be tested in modern distributions. I have added one issue to the 0.9.3 milestone, namely a popup on "low battery". I have hit that as a user before and that indeed seems quite annoying and worth removing/disabling. Please give master a test, it might end up being the next release ;)

**Comment by dvzrv** [comment]
I'd be happy to move it to Arch Linux' [community] then!

**Comment by francoism90** [comment]
Any update on this? :)
Would love to have a new release.

**Comment by dvzrv** [comment]
Is this project acually still alive? I'm considering moving this to the main Arch repository, but I don't want to maintain a zombie package...

Since 0.9.2 there have been more than 200(!) additions to this software and this was in 2013. Since then there has been *no* movement from @pwr and also no release. Is he still alive? Who is maintaining this project?

**Comment by Lekensteyn** [comment]
I don't have admin access and GitHub support could not grant it. I suppose that the best option is to create a new organization (just did it: https://github.com/pwr-Solaar as in "power Solaar" :D), then migrate the repo.

Unfortunately, issues and PRs cannot easily be migrated. So before migration, I would like to have all PRs reviewed and merged or closed. Because commits may refer to a number, I guess it would be best to create dummy issues in the new repo which just link to those in this repo.

After that is settled, perhaps a new release could be made in a few weeks?

**Comment by jasontibbitts** [comment]
Any movement here is good news.  Of course, this repository is itself merely a fork of an earlier repository so another move isn't really a big deal.  I will happily update the Fedora packaging as soon as a move is made.  Hopefully more than one person will be granted admin credentials this time around.

**Comment by ArchangeGabriel** [comment]
Believe me, @Lekensteyn knows his stuff when it comes to moving a dead repo to a new organisation because of management issues. ;)

**Comment by dvzrv** [comment]
I'm happy to hear about the move! @Lekensteyn thanks!

**Comment by Lekensteyn** [comment]
@ArchangeGabriel That worked well because of a good community, let's try that here as well :-)

@jasontibbitts I plan to add at least @jrbenito as admin. Are there other volunteers who are willing to review code and issues?

I started merging/closing some PRs, there are some remaining which probably needs to be closed/reopened in the new repo. @tomswartz07 That issue mover project looks like a one-by-one transfer of issues. My current requirements (where issues cover PRs as well) are:
- Maintain the same issue IDs (to ensure that commit messages mentioning `#123` still point to a related issue).
- Link from the new issue to the original issue.
- Link from the original issue to the new issue and close the old issue.

My plan is:
- Create new issues in the new repo, copying just the title and link to the original issue. Keep it simple, do not even try to copy the first description nor any comments. Maybe do copy tags?
- Maybe tag the new issue with "migrated"?
- After creating new issues for all old issues, close and lock old issues.
- If the original issue was closed, close the new issue as well.
- If the original issue was **not** closed... What to do? I am currently leaning towards closing.
- Maybe after migrating all issues, create a new issue in the new repo that summarizes the reasoning for the migration and states the future plan?

In any case, a comment must be left to help the community figure out where to go. Proposal for closing comments in the old repo:

**Closed** issue/PR:

    This issue was moved to https://github.com/pwr-Solaar/Solaar/issues/[issue].

**Open** issue (maybe with the "For more info" line removed?):

    Hi! This issue was moved to https://github.com/pwr-Solaar/Solaar/issues/[issue].
    If the reported issue is still valid, please consider reopening the new issue.
    For more information on this mass migration, see <link to one issue in new repo>.
    Thank you for your interest!

**New** issue:

    This issue was originally reported at https://github.com/pwr/Solaar/issues/[issue] by @[user].
    Further discussion may take place here.

**New** issue (for PR):

    This pull request was originally opened at https://github.com/pwr/Solaar/pulls/[issue] by @[user].

The Github API seems reasonable enough to use:
- Retrieve all old issues: https://developer.github.com/v3/issues/#list-issues-for-a-repository
- Create issue: https://developer.github.com/v3/issues/#create-an-issue
- Close old issue (`state=closed`): https://developer.github.com/v3/issues/#edit-an-issue
- Lock the old issue (`lock_reason=resolved`): https://developer.github.com/v3/issues/#lock-an-issue

**Comment by tomswartz07** [comment]
I'd be more than happy to test stuff. I'm on arch here, and I build from the git source with my PKGBUILD, so it's pretty trivial for me to grab and test things.

@Lekensteyn let me know if you need help moving the PRs and/or testing stuff. I'll help out where I can.

**Comment by trinitronx** [comment]
@Lekensteyn : Just got a K780, so happy to test that #319 works.  Maybe also test resolution of #298

**Comment by TheComputerGenie** [comment]
Release plan involves _actual changes_, **there hasn't been a new commit in over 5 years**, not sure what you folks are on about....

**Comment by lbeltrame** [comment]
Last commit in master is from 15th August.

**Comment by Jeansen** [comment]
@TheComputerGenie u r free to join and contribute ... :smile:

**Comment by Lekensteyn** [comment]
I still plan to migrate this repo to a new repo (thanks Github for making this difficult...) and cut a release after that, but at the moment I have other priorities. Sorry about that, thank you for your patience and understanding :)

**Comment by reuvenpo** [comment]
Are there any plans / roadmaps / vague-expectations about the future of this project? I would love to see it live-on, since Logitech mice are pretty good and I'd love to use one on my debian system, using drivers from an OS repository  (that is, with new versions which support the mice I'm thinking of using).

**Comment by MagicFab** [comment]
If/when anyone wants to help with updating / maintaining the Debian packages, check #288.

**Comment by TheComputerGenie** [comment]
> Last commit in master is from 15th August.

There's a reason I used the words:
'to the OP branch'
and even put them **in bold letters**
The original post (OP) links to 0.9.2...master 
**Latest commit edc563e on Jul 24, 2013** 
Please, in the future, read my feken words

This entire thing should have been closed at:

> @Lekensteyn added this to the 0.9.3 milestone on Feb 2

**Comment by andras-tim** [comment]
Slightly Off:
I have found a new petition about Logitech supports officially the Linux system OS... Sorry guys, but I hope! 

https://www.change.org/p/logitech-logitech-support-for-linux

**Comment by Lekensteyn** [comment]
@andras-tim Logitech devices work out-of-the-box, a petition like that does not seem very useful.

**Comment by andras-tim** [comment]
@Lekensteyn, yes, you are right, but not with all features.

For example:
* I can't use the gesture button on my Logitech Triatlon mouse
* and I can't set properly the proximity sensor + backlight or I can't customize the top-left wheel on my Logitech Craft

**Comment by trinitronx** [comment]
@Lekensteyn :

> @andras-tim Logitech devices work out-of-the-box, a petition like that does not seem very useful.
> 

Agreed!

> Still no progress on the repo migration unfortunately, I've other higher priority tasks. If someone has a tool that is known to perform a migration like [#407 (comment)](https://github.com/pwr/Solaar/issues/407#issuecomment-412283574), that would help.

Seems like the requirement for issue numbers to match is a bit too much.  Most tools like [IQAndreas/github-issues-import][2], [google/github-issue-mover][3], or [buildo/gh-issue-mover][4] seem to move issues across repos, but make no guarantees about issue numbers.

At least two of these work with ReadOnly access to the original repo, and ReadWrite / Admin on the new target repo:

- [IQAndreas/github-issues-import][2]
- [buildo/gh-issue-mover][4]

The Google AppSpot tool looks like it requires owner permissions on the [original repo][6], as does the new [official GitHub issue mover tool][7].  The Google one does appear to add reference links as you want, yet it does so on the original repo and tries to close the issue which is probably why it requires owner / admin permissions.

Perhaps if the issue numbering and reference links are hard requirements, contacting GitHub support and asking about the new [issue transfer][5] feature in this use case:  ReadOnly on original repo, ReadWrite / admin on new repo.

It is likely that only someone with access to the GitHub issue database could guarantee issue numbers could match up.  However, I doubt that issue number would matter enough to worry about.  Most repos that have changed ownership or maintainership via forks just start over.  Even some large projects that migrated their repos with admin access such as Ansible moved issues without regard to numbering, or simply used bots to auto-close and expire old issues.  I remember when they moved [ansible/ansible-modules-extras](https://github.com/ansible/ansible-modules-extras) into the core [ansible/ansible](https://github.com/ansible/ansible) repo, they just closed a bunch of open Pull Requests (including some of mine), and that code just never made it into the core repo.  Although frustrating, I realized that the Zen concept of "Letting Go" applied here... these changes did not end up being that valuable anyway (at least to me).

Seems like this use case is very widespread in the Open Source community unfortunately, given the tendency for many repo owners to go AWOL, forget about projects, or simply not have enough time to maintain so many projects without setting up a community ownership path forward.  The main way always has seemed to be: just fork & maintain the new code in another repo... yet issues are not usually copied in this method.

[1]: https://stackoverflow.com/a/53091647/645491
[2]: https://github.com/IQAndreas/github-issues-import
[3]: https://github.com/google/github-issue-mover
[4]: https://github.com/buildo/gh-issue-mover
[5]: https://blog.github.com/changelog/2018-10-30-issue-transfer/
[6]: https://github.com/google/github-issue-mover/issues/12
[7]: https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by tomswartz07** [comment]
I'm not sure I fully understand the need to copy all existing issues and such across to the new, maintained fork. Can someone share the thought process behind this?

As @trinitronx says:
> The main way always has seemed to be: just fork & maintain the new code in another repo

It seems that @Lekensteyn has some access to the repo management, is that true?
If that's the case, may I suggest that we just update the `README.md` to point to the new forked repo, and move forward from there?

RE:
>a new petition about Logitech supports officially the Linux OS

Honestly, I'd prefer to continue using this FOSS version. Who knows what kind of data-mining nonsense that Logi will embed in their (probably) binary release. :smirk: 

As mentioned in my previous comments, I'm more than happy to assist with getting this package back up and maintained again.
This is a great opportunity for all of us to set up management in case the owner goes AWOL (or gets busy with life).

**Comment by walterramjet** [comment]
i'm really getting tired of seeing Solaar mouse popping up every time my mouse decides to move

**Comment by WhyNotHugo** [comment]
Given that the original author hasn't been active in **years**, has anyone reached out to GitHub support?

They might make an exception and move/clone the entire project (eg: the repository + issues, etc) if asked politely, especially given the legitimate interest to move keep this alive expressed here.

**Comment by SlySven** [comment]
@pwr's last action on this repository was https://github.com/pwr/Solaar/issues/91#issue-16937887 18 July 2013... :open_mouth:

**Comment by Lekensteyn** [comment]
Update: as of July 2nd, the repository has been transferred to a new location (thanks @pwr!) and @FFY00 has been added as another dev/admin. A roadmap is still TBD, but at least the bus factor has been reduced now :)

**Comment by winny-** [comment]
It might be worthwhile to cut a new release if only so the project gets feedback on the last 5 years worth of commits from downstream packagers and users. Grats on the progress so far :)

**Comment by reuvenpo** [comment]
Where is the new repository?

**Comment by FFY00** [comment]
@reuvenpo it's here. The old link was https://github.com/pwr/Solaar, if you try to access you will be redirected here. We didn't create a new repository, we just moved it.

**Comment by reuvenpo** [comment]
Oh! I didn't realise that was possible! Cool

**Comment by FFY00** [comment]
It is but only the owner of the repository can do it. That's why we waited for Daniel.

**Comment by daehyeok** [comment]
@FFY00 Could you change repo desc?
It include old broken github.io page. it should change to https://pwr-solaar.github.io/Solaar/ 

![image](https://user-images.githubusercontent.com/1310758/61490778-8da80a00-a962-11e9-88a4-7f556c98adf5.png)

**Comment by daehyeok** [comment]
@FFY00 colud you change repo desc?
it's include old broken github.io link. it should change to https://pwr-solaar.github.io/Solaar/
![image](https://user-images.githubusercontent.com/1310758/61491008-12932380-a963-11e9-99f5-e5d041d3b8ff.png)

**Comment by FFY00** [comment]
Done!

**Comment by Lekensteyn** [comment]
@FFY00 just did a 1.0.1 release, I think the objective of this ticket has completed!
