### ISSUE TITLE
fn-swap resets to default after keyboard reconnect

### ISSUE THREAD

**Issue by hxss** [pwr-Solaar/Solaar#437]
Hello. First thanks very much to all who contributed in writing this manager!
I'm using k780 that have multi-device futures and I want to use traditional F1-12 button actions by default.

On arch linux fn-swap setting for my keyboard now available only in [git version](https://aur.archlinux.org/packages/solaar-git/). And it's working!

But every time I'm switch keyboard connection to other device and return to this pc, I need to reset fn-swap to false because its doesn't applies automatically.

Can you fix it?

P.S.: git version, unlike [usual aur pkg](https://aur.archlinux.org/packages/solaar/) doesn't send notify on kb connection. Maybe problem in this?

**Comment by hxss** [comment]
and if kb wake up from sleep its also require my actions with fn-swap.

**Comment by solispauwels** [comment]
+1

**Comment by solispauwels** [comment]
I have the same problem, what I do for now is to assign a keyboard shortcut the following command

~/Solaar/bin/solaar config 1 fn-swap no

We can may trigger that when the keyboard reconnect, but how?

**Comment by hxss** [comment]
after upgrade solaar-git (r961.59b7285-1 -> r985.b852903-1) the keyboard works perfect! I don't need to press my shortcut every time kb wake up! I can switch off/on kb or disconnect/connect receiver and fn-buttons will work as they should. Thank you @pwr!

**Comment by hxss** [comment]
>with the master branch
>solaar-git (r961.59b7285-1 -> r985.b852903-1)

**Comment by jonashungershausen** [comment]
@hxss I'm not aware of anything that's more up-to-date than the master branch. But please correct me if I'm wrong. I'd really like this issue to be fixed on Ubuntu.

**Comment by noblehng** [comment]
I just got a K780 and had the same issue. It can be solved by creating an udev rule.

Using solaar:
`ACTION=="change", SUBSYSTEM=="power_supply", TEST=="online", ATTR{manufacturer}=="Logitech", ATTR{serial_number}=="405b-*", ATTR{online}=="1", RUN+="/usr/bin/solaar config %m fn-swap 0"`

Or using shell:
`ACTION=="change", SUBSYSTEM=="power_supply", TEST=="online", ATTR{manufacturer}=="Logitech", ATTR{serial_number}=="405b-*", ATTR{online}=="1", RUN+="/bin/sh -c 'echo -n -e \"\x11\xff\x0c\x1d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\" >> /dev/hidraw%m'"`

**Comment by mbirth** [comment]
With Solaar 1.0.1, I only have this Fx-Swap reversal for 1-2 seconds after a reconnect. E.g. if I wake up the keyboard with the F12 key, it will turn up the volume but 1-2 seconds later, F12 will suddenly start sending the F12 keycode. Same after switching to my PC using the white keys - for 1-2 seconds after switching, the F-keys will send the underlying multimedia keycodes until they start sending the F-keycodes.

Is this a problem with Solaar or the keyboard? (Firmwares of receiver and kbd are up-to-date.)

**Comment by pfps** [comment]
@mbirth Here is what I think is going on.   Solaar is remembering that you have Fx-Swap set to have the function keys send F-keycodes.  When  the keyboard wakes up it wakes up with Fx-Swap set to have the function keys send the special codes.  Solaar then tries to set Fx-Swap the way that it thinks you want it set but it takes a second or two for Solaar to set up the keyboard.  When the keyboard goes to sleep it goes back to its default status.  (I am not sure just what would trigger the keyboard to reset to defaults.  There are several keyboard state changes that could cause this, ranging from disconnecting to physically turning the keyboard.  One way to check would be to have Solaar set the keyboard to the non-default state, then kill Solaar, and see what happens when the keyboard connects.  If the keyboard starts out sending special keys and does not switch to F-keys then that would be evidence for my conjecture.

**Comment by mbirth** [comment]
@pfps It seems you were right. When exiting Solaar, the keyboard stays in the "media keys" mode. Once I start Solaar, the F-keys start to work. Too bad there isn't a way to permanently switch the keyboard to Fx-Swap.

**Comment by pfps** [comment]
@mbirth I think this is as good as it can get.  If you agree please close this issue.

**Comment by mbirth** [comment]
@pfps Is there a way to intercept the keypress and either resend it with the correct keycode (probably means Solaar would have to know the mapping for each keyboard) or drop it, so the keypress doesn't make it through?

Also, I don't have a "Close" button.

**Comment by pfps** [comment]
@mbirth  I don't think so.  As far as I know, Solaar doesn't sit between the device and the Linux input system.  Instead it sort of sits off to the side.   So, again as far as I know, Solaar can't change the keypresses that the Linux input system sees.
Aah, you can't close because you are not the original poster.  If there is no more activity on this issue, I'll close it in about a month.

**Comment by FFY00** [comment]
Yes, this is never going to be implemented in Solaar. What we will do is have a Logitech daemon, so that it can manage your devices and apply these settings when the device wakes up.

**Comment by pfps** [comment]
Closed as partially addressed by PR #649 and remaining portion out of scope for Solaar.
