### ISSUE TITLE
Refactor documentation

### ISSUE THREAD

**Issue by FFY00** [pwr-Solaar/Solaar#591]
I would like for the documentation to be refactored, making it more consistent and up to date.

Some points to take into account:
  - [x] Update the description
  - [x] Update information about available packages in distributions
  - [x] Update installation instructions
  - [x] Update "Known Issues" section
  - [x] Remove redundant pages (some pages have been removed)
  - [x] Remove external documentation documents (those should be in a separated place)
  - [x] Document supported receivers
  - [x] Example on how to add new receivers
  - [x] Example on how to support new HID++ 2.0 features
  - [x] Verify old kernel versions (pre-5.2) and adjust the dependency list  (adjusted documentation to say 5.2 or newer)

**Comment by pfps** [comment]
I made some changes to devices.md, index.md, and installation.md.  This addresses some of the above points, but not all.  it should at least cut down on the bug reports for old versions of solaar.

I need help on actually installing solaar to /usr/bin as I don't understand how to do this.

I'm attaching a git diff of the changes.  I'll set up a fork so that you can also pull from there.

[docs-diff.txt](https://github.com/pwr-Solaar/Solaar/files/3974465/docs-diff.txt)

**Comment by FFY00** [comment]
That would be great, thanks!

**Comment by pfps** [comment]
@FFY00 There have quite a few changes to the documentation.  What more should be done?

**Comment by FFY00** [comment]
I haven't been keeping track of everything that has been done, can up mark the checkmarks?

**Comment by pfps** [comment]
@FFY00 I removed the logitech files and pointed to the Google drive folder and added a couple of paragraphs on adding receivers and devices to devices.md in #849

**Comment by FFY00** [comment]
Thank you! If you have time you can go over the documentation and remove duplicated stuff. Less important, you can test Solaar with older kernel versions and document if it works, I would do 4.9, 5.0, 5.2, and 5.4.

**Comment by pfps** [comment]
@FFY00 I don't think there is much duplication left.

**Comment by pfps** [comment]
It would be useful to have the current version of Solaar testing on CentOS or RHEL.

**Comment by FFY00** [comment]
I can't do it, but feel free to.
