### ISSUE TITLE
Unable to pair Logitech MX Master 3

### ISSUE THREAD

**Issue by biographie** [pwr-Solaar/Solaar#667]
**Information**

- Solaar version: 1.01
- Distribution: Manjaro 18.1.5
- Kernel version (ex. `uname -srmo`): Linux 5.4.15-2-MANJARO x86_64 GNU/Linux
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 579B9757
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 0 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

```

**Describe the bug**
I am unable to pair Logitech MX Master 3. When I first installed Solaar it was paired however it wasn't showing the batter level. So I thought un-pairing and re-pairing might solve the problem but now I can't pair the device at all. It just times out.

**Comment by FFY00** [comment]
Did you put the device in pairing mode? Long button press until the led starts blinking?

**Comment by biographie** [comment]
Hah, that worked! Thanks.
For some reason, now I'm having the same issue as the one here https://github.com/pwr-Solaar/Solaar/issues/622

**Comment by pfps** [comment]
OK, closing this issue.  

Issue #622 is a puzzler, though.  I only see it once in a while.  If you could run with -dd and report the output when you see the problem, that *might* help.

**Comment by steveklett** [comment]
_I see that this issue is closed, but I'm having the exact same issue and unsure if proper etiquette is to comment on a closed issue (as I am here) or start a new issue._

I can't pair my S3 device. I've paired two other logitech devices without a problem.
I've put the mouse into pairing mode (fast flashing light) and attempted the Solaar pairing scan procedure numerous times without luck.

I'm VERY new to Linux (10 hours) so perhaps I'm missing something obvious.

System info:
```
System:
  Host: steve-Latitude-E7470 Kernel: 6.8.0-38-generic arch: x86_64 bits: 64
    compiler: gcc v: 13.2.0 clocksource: tsc
  Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.41 wm: xfwm4 v: 4.18.0
    with: xfce4-panel tools: light-locker vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
```
