### ISSUE TITLE
Battery icon misleading in Pop theme

### ISSUE THREAD

**Issue by BaronKrause** [pwr-Solaar/Solaar#768]
I noticed for the past week after an update that the Git versions battery icon always shows as low (looks like roughly 25% and the color is orange) but it still reports the fully charged mouse correctly as being at 100%. It shows this in the system tray and inside Solaar when you open it up (showing the orange low battery icon right next to the 100% battery level readout).

Just figured I would report it incase it was unknown!

Currently using 1.0.2rc2 from the Git PPA on Pop OS.

**Comment by pfps** [comment]
This should not happen.  Please provide output of `solaar -dd show` and screenshot of the main window when the problem is occurring.

**Comment by pfps** [comment]
You might also check that the battery icons in your GTK icon theme are correct, using gtk3-icon-browser.  The battery icons should be in the Other group, and are battery-{empty,caution,low,good,full}[-chaging] and battery-missing.

**Comment by BaronKrause** [comment]
> You might also check that the battery icons in your GTK icon theme are correct, using gtk3-icon-browser. The battery icons should be in the Other group, and are battery-{empty,caution,low,good,full}[-charging] and battery-missing.

Ok, it is the default theme. Seems the Pop theme has many size versions of the icon "battery" which on closer inspection looks like a duracell copper top battery and not really a low battery indicator. But it is different than the full battery icon for the laptops battery that's right next to it, which looks exactly like what the Solaar icon use to when full (solid white).

The empty,caution,low,good,full all exist in that theme but only as the "symbolic" variants (like "battery-full-symbolic.svg), everything else in the theme is just "battery.png" and they all look like the aforementioned duracell icon.

**Comment by pfps** [comment]
The problem is that system tray implementations do not handle symbolic icons correctly so in dark themes the icons are practically invisible.  There was a complex scheme to determine which icons are present, but that stopped working because the first check was for symbolic icons and hicolor (which is supposed to be inherited by every icon theme) has symbolic icons.   So users of dark themes ended up with invisible icons.
The right solution is to fix system tray implementations.  But the system tray is deprecated in Gnome, so that's not going to happen for all window managers.  XFCE's system tray has a fix, but that's not going into a real release until the fall.  
Adding a command-line option to prefer symbolic icons is non-trivial.  If you want you can tell GTK to prefer symbolic icons by adding
```
* { -gtk-icon-style: symbolilc; }
```
to your ~/.config/gtk-3.0/gtk.css file.  That switches to symbolic icons everywhere.  (It would be nice if you could do this by application, but that doesn't work due, again, to limitations in implementations of appindicator and system trays.)  You will probably have to log out and log in to make this take.

**Comment by pfps** [comment]
OK, OK, you twisted my arm.  :-)  (Actually I thought of a reasonable way to implement preferring symbolic icons, which I should have thought of a while ago.)

I just implemented a new option `--battery-icons=symbolic` to prefer symbolic battery icons.

Please test it out by cloning my Solaar repository and running from the icons branch via:
```
git clone https://github.com/pfps/Solaar.git
cd Solaar
git checkout icons
bin/solaar --battery-icons=symbolic
```
(You have to kill any running Solaar first, of course.)
