### ISSUE TITLE
“Missing required package 'python-pyudev'” on Ubuntu 20.04

### ISSUE THREAD

**Issue by nclm** [pwr-Solaar/Solaar#782]
**Information**
- Solaar version: `1.0.1+dfsg-3`
- Distribution: Ubuntu 20.04
- Kernel version: `5.4.0-29-generic x86_64`

**Describe the bug**
Solaar doesn’t launch (any more). When trying it from the command line, I get this error:
```
Solaar: missing required package 'python-pyudev'
```
However, the package `python3-pyudev` is installed on my system.

**Additional context**
I haven’t used my keyboard for a couple of weeks, and now that I want to use it again, I realised Solaar does not work any more. What I did since last time is to upgrade my Ubuntu to version 20.04.

**Comment by pfps** [comment]
This is probably a python 2 vs 3 problem.   Either use a newer version of Solaar or try running Solaar with python3.

**Comment by pfps** [comment]
If you already have Solaar installed, one way to install (for yourself only) and run the current (as of 18 May 2020) version of Solaar is via
```
pip install --user solaar==1.0.2rc3
~/.local/bin/solaar
```
This doesn't mess with any system stuff.

**Comment by trinitronx** [comment]
> pip install --user solaar

For Ubuntu 20.04 with `python3-pip` (or other distros without `pip` linked to `pip3`):

```
pip3 install --user solaar
```

**Comment by Easy121** [comment]
I encountered the same problem (`Solaar: missing required package 'python-pyudev'`) today, when I tried to run an old release (Solaar 1.1.1) downloaded from github release with `bin/solaar -dd config "MX Keys" change-host 1`. And in my system, `python3-pyudev` is already installed. 

Solution: I realized that I'm using `pyenv` with python 3.9.13, instead of the system python. So after running `pyenv local system`, Solaar 1.1.1 can be tested without error.
