### ISSUE TITLE
DPI

### ISSUE THREAD

**Issue by wojciechGaudnik** [pwr-Solaar/Solaar#801]
Hi,
Where you define the started 1000 dpi , I have to change this variable, because when I switch mouse constantly return into this 1000 dpi state.

**Comment by pfps** [comment]
I'm not sure exactly what the problem that you are describing is.

Solaar keeps track of the settings of your devices and restores them to their last known state.  It does this so that the changes you make persist and you do not have to redo them time after time.

You should be able to change this setting to some other value in Solaar and then that value will be used in future.

**Comment by wojciechGaudnik** [comment]
When I plug-in and plug-out mouse, settings always return to this 1000 dpi. I Have try edit settings file. Right now I give up and the last thing that I could figure out is that what I asked. Is there some "variable" that you set up to 1000 dpi in the program?

**Comment by pfps** [comment]
That is the expected behaviour.  If  you want a different value you should use Solaar to change the DPI settings in the Solaar main window, and then that value will be the one that is restored.

**Comment by wojciechGaudnik** [comment]
Yes, I know, but it doesn't work.

**Comment by pfps** [comment]
Please file a bug report, with all the requested information.  There is a bug - #726 - in older versions of Solaar related to devices that have only part of their features described.
