### ISSUE TITLE
Bug on Keyboard K360

### ISSUE THREAD

**Issue by papusone** [pwr-Solaar/Solaar#808]
**Information**

- Solaar version 1.01:
- Distribution: UBUNTU 20.04 LTS
- Kernel version (ex. `uname -srmo`): `5.4.0.37`
- Output of `solaar show`: No Error Message
```
OUTPUT HERE
```Keyboard detected, but always off at any star of session ! Must set the switch to OFF and ON for correct detection ! 
My Other Peripheral MX 25 is correctly detected !
Nevertheless, excellent program and very useful, Thanks !

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by pfps** [comment]
Please provide complete output of `solaar show`, as requested, preferably when you are experiencing the issue.

But I expect that the problem is not in solaar.  Solaar does not do anything to activate devices, which are supposed to wake up and come online when they are used, and go into a low-power state when they are not used for some time.  Pressing a key on the keyboard should be enough to wake it up.

What happens without Solaar running?  Do you need to turn the keyboard off and on before you can use it?

**Comment by papusone** [comment]
Hello !
Thanks for your answer ! No , Without Solaar running, keyboard work's fine ! And it works also with solar, but it appears grayed out, and need to off and on, for having battery level and for use function keys with the second level !

**Comment by pfps** [comment]
So even when you are typing on the keyboard it is still greyed out in Solaar's main window and the Wireless Link says offline?  If so, it may be that the device is sending a wake-up notification that Solaar does not understand.  
Diagnosing the problem is going to have to start with collecting some traces.  First please update to Solaar 1.0.2 or the current git version from the Ubuntu Solaar PPA mentioned in https://github.com/pwr-Solaar/Solaar
Then start Solaar as `solaar -dd` some way that you can copy the output..  Try to use your Logitech mouse as little as possible as moving the mouse will cause Solaar to output a line for each mouse movement.   Type on the keyboard a bit.  Then attach the Solaar output to a comment in this issue.

**Comment by papusone** [comment]
Hello Again !
It seems that the 1.02 Solaar version solved the Problem ! Thanks for your Assistance !
