### ISSUE TITLE
Status icon could be conflated with that of system power.

### ISSUE THREAD

**Issue by anubeon** [pwr-Solaar/Solaar#84]
Currently, Solaar appears to use the some generic battery icon as is used by the systems default power indicator. I'd suggest switching to the gpm/xfpm-mouse-\* icons in stead, to avoid conflating the two. I realise of course that solaar caters to keyboards and other devices besides mouses/mice_, but I would imagine that there are a hell of a lot more wireless logitech mouses/mice_ out there than keyboards, etc. Besides, gpm/xfpm-mouse-\* looks a damn sight better than gpm/xfpm-keyboard-\* (at least with respect to Ubuntu's default icon theme).

*For the love of atheismo, which is it?! ;-)

P.S.: Thank you for taking the time to develop this. This is one functionality that I have sorely missed since switching to linux some years ago. It's long overdue.

**Comment by chrisl8** [comment]
I thought Solaar wasn't working. It would start and then go away.
Then I realized I had two battery icons in my system tray. Sure enough, one of them is Solaar.
I though this was a bug, but I guess it is on purpose?

My two cents:
I would be happiest to just see the pretty Solaar icon instead of the second battery. The icon doesn't need to do anything fancy other than just reassure me that Solaar is running and give me a place to click to change settings.
I do want the icon though. If it was hidden I'd worry it had quit.

**Comment by bogdan-radocea** [comment]
If there is such a problem with solaar when auto/smart picking the icon according to the current theme, then please give us an option to pick our own icons for the tray. Have some list of built-in icons that we can choose from.

**Comment by pfps** [comment]
This issue is likely to become worse as the scheme to pick the "best" icons is being removed because it was causing problems in dark themes.
