### ISSUE TITLE
Use a translation service

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#891]
**Information**

I would propose that the program is translated through an external crowdsourcing service. That could localize the program for a lot more languages than the current dev-base could ever be able to do.

**Describe the solution you'd like**

The chosen solution should integrate well, and should move translations out of ordinary code maintenance.

I have previously used [Translatewiki](https://translatewiki.net), but for a gettext-based program it could be better to use [Crowdin](https://crowdin.com) due to the integration with [poedit](https://poedit.net/). There are several other services too.

Note that I have not used Translatewiki for `gettext`-style localization, but my understanding is that it would integrate well. (I can check with the devs.)

It could be wise to consider a service with well-supported machine translation software, and not only a translation memory like in `poedit`. Translatewiki is pretty amazing in this respect.

**Comment by pfps** [comment]
This looks like a good idea.  There needs to be someone who is willing to set it all up.

**Comment by jeblad** [comment]
I guess that points to me, but that would be an implicit “no”. So closing.

**Comment by muzena** [comment]
@pfps
I enabled Solaar translation system on launchpad.
https://translations.launchpad.net/solaar-unifying/trunk/+translations
Launchpad don't have option for auto commit translation to github.
So before new release of Solaar you have option to manually download tarball with po's file and commit/upload them to github.
Manual synchronization -> download

**Comment by pfps** [comment]
So this fills in strings that are not translated.  Sounds good.  Let me see what can be done.

**Comment by pfps** [comment]
I downloaded the files, I think, but I don't see any new translations.  There are new messages but all the new messages have no translation.  Should I be expecting new translations?

**Comment by pfps** [comment]
One annoyance is the different file names.  Is there any way to fix that?

**Comment by muzena** [comment]
@pfps 
Solaar code is imported to Launchpad as git control system, but it can be imported as bazzar control system.
Bazzar controll system can automatically manage translation system, it auto syncs github with launchpad and sync code together with translation system and update pot and po files without:

>  One annoyance is the different file names.

Like in this [Freetux example](https://code.launchpad.net/freetuxtv)

lp:freetuxtv   translations are automatically sync with translation system, and when translator made changes to po file it auto sync to   lp:~freetuxtv/freetuxtv/translations branch.

I can try to import as bazzar control system but I need to completely delete [git system control import](https://code.launchpad.net/freetuxtv/+git) (this removes auto build recepies for PPA)
because there is some bug in [import system](https://code.launchpad.net/~freetuxtv/freetuxtv/freetuxtv)
https://bugs.launchpad.net/bzr-git/+bug/1313861
It failed to import code as bazzar

If I delete git control system and try to import as bazzar there is no guarantee that it will succeed, maybe it failde because of this [import bug.](https://code.launchpad.net/~freetuxtv/freetuxtv/freetuxtv)

**Comment by muzena** [comment]
I think there is typo in:
Ajustment and Rachet
lib/logitech_receiver/settings_templates.py:_DPI_SLIDING = ('dpi-sliding', _('DPI Sliding Ajustment'),
lib/logitech_receiver/settings_templates.py:_SMART_SHIFT = ('smart-shift', _('Scroll Wheel Rachet'),
docs/usage.md:Scroll Wheel Rachet		 | Shift wheel ratchet on and off based on wheel speed
