### ISSUE TITLE
Put "dangerous" features under warning

### ISSUE THREAD

**Issue by barolo** [pwr-Solaar/Solaar#978]
**Is your feature request related to a problem? Please describe.**

I had a particularly hectic conference where I had to switch between the two PCs constantly and fast [ using host switch feature ] and when doing that via GUI I've disabled left mouse click accidentally while being completely oblivious to it,  which was really bad [ as you can imagine ] and took me a bit to figure it out.
[ I will do that guiless next time, just didn't have time to prepare for that particular event ]

**Describe the solution you'd like**
Perhaps put it behind some kind of a pop-up warning about what's to happen?

**Comment by pfps** [comment]
I sympathize.  But what is the right way to do this?  I'm trying to abide by the Unix philosophy and not include "nanny" features.

One simple thing to do would be to reverse the order of the keys in the menu so that the left button doesn't show normally.  But that would mean that any function keys would show up in reverse order for many keyboards.  A slightly more complex thing to do would be to swap the order of left and right buttons.  A third thing to do would be to suppress the left and right buttons.  But that is a "nanny' feature and also prevents swapping the left and right buttons.

**Comment by barolo** [comment]
Maybe a "lock settings, prevent modificiation" type toggle? Seems like a pretty common thing, or just some command line switch

**Comment by pfps** [comment]
Yes, a method for locking any setting would be useful.  Now how to implement it. ...

**Comment by pfps** [comment]
@barolo One way to do this is to make the setting label sensitive.  A click on it changes the sensitivity of the setting value.  If the tooltips are set up correctly settings could be insensitive by default.

**Comment by barolo** [comment]
I'm up for trying anything ;)

**Comment by pfps** [comment]
Try PR #980 
It still needs a bit of polish, but the basic idea is that you click on a setting name to toggle whether the setting is active.  Your choices persist.  So try moving your MX Master between different machines (BT connect, receiver connect) and try killing and restarting Solaar.  The initial default is that settings are active.
